// Copyright mzoesch. All rights reserved.

#pragma once

DECLARE_INLINE_LOG_CATEGORY( LogCarnifex,               Trace )
DECLARE_INLINE_LOG_CATEGORY( LogChunkGeneration,        Trace )
DECLARE_INLINE_LOG_CATEGORY( LogChunkManipulation,      Trace )
DECLARE_INLINE_LOG_CATEGORY( LogChunkMisc,              Trace )
DECLARE_INLINE_LOG_CATEGORY( LogChunkValidation,        Trace )
DECLARE_INLINE_LOG_CATEGORY( LogController,             Trace )
DECLARE_INLINE_LOG_CATEGORY( LogFontSubsystem,          Trace )
DECLARE_INLINE_LOG_CATEGORY( LogFrontEnd,               Trace )
DECLARE_INLINE_LOG_CATEGORY( LogGenPrevAssets,          Trace )
DECLARE_INLINE_LOG_CATEGORY( LogGuardedMain,            Trace )
DECLARE_INLINE_LOG_CATEGORY( LogHyperlane,              Trace )
DECLARE_INLINE_LOG_CATEGORY( LogJafgInternal,           Trace )
DECLARE_INLINE_LOG_CATEGORY( LogLackey,                 Trace )
DECLARE_INLINE_LOG_CATEGORY( LogMaterialSubsystem,      Trace )
DECLARE_INLINE_LOG_CATEGORY( LogNetwork,                Trace )
DECLARE_INLINE_LOG_CATEGORY( LogObjectInternal,         Trace )
DECLARE_INLINE_LOG_CATEGORY( LogObjectPackager,         Trace )
DECLARE_INLINE_LOG_CATEGORY( LogPlatform,             Verbose )
DECLARE_INLINE_LOG_CATEGORY( LogPlatformMisc,           Trace )
DECLARE_INLINE_LOG_CATEGORY( LogRecipeSystem,           Trace )
DECLARE_INLINE_LOG_CATEGORY( LogRhi,                    Trace )
DECLARE_INLINE_LOG_CATEGORY( LogRunnable,               Trace )
DECLARE_INLINE_LOG_CATEGORY( LogStrikeSystem,           Trace )
DECLARE_INLINE_LOG_CATEGORY( LogSubsystemCollection,    Trace )
DECLARE_INLINE_LOG_CATEGORY( LogSurface,                Trace )
DECLARE_INLINE_LOG_CATEGORY( LogSystem,                 Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTasks,                  Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTaskSystem,             Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTaskUtility,            Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTemporal,               Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTesting,                Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTestingFramework,       Trace )
DECLARE_INLINE_LOG_CATEGORY( LogTextureSubsystem,       Trace )
DECLARE_INLINE_LOG_CATEGORY( LogUserInput,              Trace )
DECLARE_INLINE_LOG_CATEGORY( LogVoxelSubsystem,         Trace )
DECLARE_INLINE_LOG_CATEGORY( LogWidgetFramework,        Trace )
DECLARE_INLINE_LOG_CATEGORY( LogWidgets,                Trace )
DECLARE_INLINE_LOG_CATEGORY( LogWorld,                  Trace )
