// Copyright 2024 mzoesch. All rights reserved.

package SolutionGenerator

import (
    "Jafg/Shared"
    "fmt"
    "os"
    "slices"
    "strings"
)

func GenerateCmakeSolution() {
    var handle *os.File = PrepareCmakeFile()
    WriteCmakeFileBody(handle)
    Shared.CloseFile(handle)

    var presetsHandle *os.File = PrepareCmakePresetsFile()
    WriteCmakePresetsFileBody(presetsHandle)
    Shared.CloseFile(presetsHandle)

    return
}

func PrepareCmakeFile() *os.File {
    fmt.Println("Preparing CMakeLists.txt file...")

    Shared.CheckRelativeFile(Shared.SolutionCmakeFile)
    var file *os.File = Shared.OpenRelativeFile(Shared.SolutionCmakeFile, true, os.O_RDWR)
    Shared.WriteToFile(
        file,
        "# Copyright 2024 mzoesch. All rights reserved.\n"+
            "# This file is automatically generated by Jafg and can be deleted with no fear.\n\n",
    )

    return file
}

func PrepareCmakePresetsFile() *os.File {
    fmt.Println("Preparing CMakePresets.json file...")

    Shared.CheckRelativeFile(Shared.SolutionCmakePresetsFile)
    var file *os.File = Shared.OpenRelativeFile(Shared.SolutionCmakePresetsFile, true, os.O_RDWR)
    return file
}

func WriteCmakeFileBody(handle *os.File) {
    if handle == nil {
        panic("WriteCmakeFileBody called with nil handle.")
    }

    var builder strings.Builder = strings.Builder{}

    WriteAllCmakeFileSharedLogic(&builder)
    WriteCmakeFileProjectSpecificSections(&builder)
    WriteCmakeFileGeneratedSection(&builder)
    WriteCmakeFileVendorSection(&builder)
    AddCustomCmakeWasmRuntime(&builder)

    Shared.WriteToFile(handle, builder.String())

    return
}

func WriteAllCmakeFileSharedLogic(builder *strings.Builder) {
    var cxxCfgs string = ""
    var cxxCfgsGoList []string
    var cxxCfgsDebug []string
    var cxxCfgsDevelopment []string
    var cxxCfgsShipping []string

    var cxxFlags_Gnu string = "-fno-rtti" // Disables RTTI
    var cxxFlags_Msvc string = "/GR-"     // Disables RTTI
    cxxFlags_Msvc += " /Zc:__cplusplus"   // __cplusplus for using the non std __cplusplus version macro.

    var cxxFlags_Debug_Gnu string = "-Wall -Wextra" // -Wpedantic" // Warnings.
    cxxFlags_Debug_Gnu += " -g" // Generate debug info .pdb files.
    cxxFlags_Debug_Gnu += " -O0" // Pessimistic optimization.
    var cxxFlags_Debug_Msvc string = "/W3" // Enable level three warnings (if needed /Wall for all warnings).
    cxxFlags_Debug_Msvc += " /Zi" // Generate debug info .pdb files.
    cxxFlags_Debug_Msvc += " /Od" // Pessimistic optimization.
    var lnkSharedFlags_Debug_Gnu string = ""
    var lnkSharedFlags_Debug_Msvc string = "/DEBUG /NODEFAULTLIB:libcmt /NODEFAULTLIB:msvcrtd"
    var lnkExecFlags_Debug_Gnu string = ""
    var lnkExecFlags_Debug_Msvc string = "/DEBUG"

    var cxxFlags_Development_Gnu string = "-Wall -Wextra" // Warnings.
    cxxFlags_Development_Gnu += " -g" // Generate debug info .pdb files.
    cxxFlags_Development_Gnu += " -O2" // Optimistic optimization for speed.
    var cxxFlags_Development_Msvc string = "/W3" // Enable level three warnings.
    cxxFlags_Development_Msvc += " /Zi" // Generate debug info .pdb files.
    cxxFlags_Development_Msvc += " /O2" // Optimistic optimization for speed.
    var lnkSharedFlags_Development_Gnu string = ""
    var lnkSharedFlags_Development_Msvc string = "/DEBUG /NODEFAULTLIB:libcmt /NODEFAULTLIB:msvcrtd"
    var lnkExecFlags_Development_Gnu string = ""
    var lnkExecFlags_Development_Msvc string = "/DEBUG"

    var cxxFlags_Shipping_Gnu string = "-Wall -Wextra"  // Enable all warnings.
    cxxFlags_Shipping_Gnu += " -O3" // Aggressive speed optimization.
    cxxFlags_Shipping_Gnu += " -ffast-math" // Floating point optimizations.
    cxxFlags_Shipping_Gnu += " -flto" // Link time optimization.
    cxxFlags_Shipping_Gnu += " -march=native" // Use the native architecture.
    var cxxFlags_Shipping_Msvc string = "/W3" // Enable level three warnings.
    cxxFlags_Shipping_Msvc += " /Ox" // Aggressive speed optimization.
    cxxFlags_Shipping_Msvc += " /fp:fast" // Floating point optimizations.
    cxxFlags_Shipping_Msvc += " /GL" // Whole program optimization.
    var lnkSharedFlags_Shipping_Gnu string = ""
    var lnkSharedFlags_Shipping_Msvc string = "/LTCG /DEBUG:NONE"
    var lnkExecFlags_Shipping_Gnu string = ""
    var lnkExecFlags_Shipping_Msvc string = ""

    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        cxxCfgsDebug = append(cxxCfgsDebug, fmt.Sprintf("Debug-%s", targ.GetSuffix()))
        cxxCfgsDevelopment = append(cxxCfgsDevelopment, fmt.Sprintf("Development-%s", targ.GetSuffix()))
        cxxCfgsShipping = append(cxxCfgsShipping, fmt.Sprintf("Shipping-%s", targ.GetSuffix()))

        continue
    }
    if len(cxxCfgsDebug) == 0 {
        panic("No targets found in cfg debug.")
    }
    if len(cxxCfgsDevelopment) == 0 {
        panic("No targets found in cfg development.")
    }
    if len(cxxCfgsShipping) == 0 {
        panic("No targets found in cfg shipping.")
    }

    for idx, _ := range cxxCfgsDebug {
        cxxCfgs += cxxCfgsDebug[idx]
        cxxCfgs += ";"
        cxxCfgsGoList = append(cxxCfgsGoList, cxxCfgsDebug[idx])
    }
    for idx, _ := range cxxCfgsDevelopment {
        cxxCfgs += cxxCfgsDevelopment[idx]
        cxxCfgs += ";"
        cxxCfgsGoList = append(cxxCfgsGoList, cxxCfgsDevelopment[idx])
    }
    for idx, _ := range cxxCfgsShipping {
        cxxCfgs += cxxCfgsShipping[idx]
        if idx < len(cxxCfgsShipping)-1 {
            cxxCfgs += ";"
        }
        cxxCfgsGoList = append(cxxCfgsGoList, cxxCfgsShipping[idx])
    }

    WriteWithIndent(builder, 0, fmt.Sprintf(`
cmake_minimum_required(VERSION 3.21...3.30)
if(${CMAKE_VERSION} VERSION_LESS 3.12)
    cmake_policy(VERSION ${CMAKE_VERSION})
endif()
find_package(Python REQUIRED COMPONENTS Interpreter)
message(STATUS "Python_EXECUTABLE: ${Python_EXECUTABLE}")
set(TARGET_PLATFORM_WIN "Windows")
set(TARGET_PLATFORM_WASM "Wasm")
set(TARGET_PLATFORM ${TARGET_PLATFORM_WIN} CACHE STRING "The platform to target.")
set_property(CACHE TARGET_PLATFORM PROPERTY STRINGS ${TARGET_PLATFORM_WIN} ${TARGET_PLATFORM_WASM})
message(STATUS "Target platform: ${TARGET_PLATFORM}.")
project(
    Jafg
    VERSION 0.0.1
    DESCRIPTION "S-Jafg"
    LANGUAGES C CXX
    )
message(STATUS "Detected C compiler: ${CMAKE_C_COMPILER}.")
message(STATUS "Detected CXX compiler: ${CMAKE_CXX_COMPILER}.")
message(STATUS "With CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}.")
message(STATUS "With CXX_COMPILER_ID: ${CMAKE_CXX_COMPILER_ID}.")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(USING_MSVC ON)
    set(USING_MINIMAL OFF)
    set(CURRENT_COMPILER_SUPPORTS_SHARED_LNK ON)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(USING_MSVC OFF)
    set(USING_MINIMAL ON)
    set(CURRENT_COMPILER_SUPPORTS_SHARED_LNK ON)
else()
    string(REGEX MATCH ".*em\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
    if(REGREX_MATCHED)
        set(USING_MSVC OFF)
        set(USING_MINIMAL ON)
        set(CURRENT_COMPILER_SUPPORTS_SHARED_LNK OFF)
    else()
        message(FATAL_ERROR "Unsupported compiler [Compiler: ${CMKAE_CXX_COMPILER}; ID: ${CMAKE_CXX_COMPILER_ID}].")
    endif()
endif()
if(USING_MSVC)
    message(STATUS "Compiling for msvc...")
    if(USING_MINIMAL)
        message(FATAL_ERROR "Cannot compile for msvc and gnu at the same time.")
    endif()
endif()
if(USING_MINIMAL)
    message(STATUS "Compiling for gnu...")
    if(USING_MSVC)
        message(FATAL_ERROR "Cannot compile for msvc and gnu at the same time.")
    endif()
endif()
set(CMAKE_CONFIGURATION_TYPES
    "%s"
    CACHE STRING "Limited configurations." FORCE
    )
if(USING_MSVC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} %s")
endif()
if(USING_MINIMAL)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} %s")
    if(NOT CMAKE_CONFIGURATION_TYPES)
        message(FATAL_ERROR "CMAKE_CONFIGURATION_TYPES is not defined.")
    endif()
    if(NOT CMAKE_BUILD_TYPE)
        message(FATAL_ERROR "CMAKE_BUILD_TYPE is not defined.")
    endif()
    message(STATUS "Compiling as ${CMAKE_BUILD_TYPE}...")
    list(FIND CMAKE_CONFIGURATION_TYPES ${CMAKE_BUILD_TYPE} INDEX)
    if(INDEX EQUAL -1 AND CMAKE_BUILD_TYPE)
        message(
            FATAL_ERROR
            "CMAKE_BUILD_TYPE is '${CMAKE_BUILD_TYPE}' but only allowed is [${CMAKE_CONFIGURATION_TYPES}]."
            )
    endif()
endif()
if(USING_MSVC)
    add_compile_definitions($<$<STREQUAL:${TARGET_PLATFORM},${TARGET_PLATFORM_WIN}>:COMPILER_SUPPORTS_SHARED_LNK>)
    set(TARGET_CPU_ARCHITECTURE "x64")
endif()
if(USING_MINIMAL)
    if(CURRENT_COMPILER_SUPPORTS_SHARED_LNK)
        add_compile_definitions(COMPILER_SUPPORTS_SHARED_LNK)
    endif()
    if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        get_filename_component(EMSCRIPTEN_ROOT_PATH ${CMAKE_CXX_COMPILER} DIRECTORY)
        set(TARGET_CPU_ARCHITECTURE "wasm32")
    else()
        set(EMSCRIPTEN_ROOT_PATH "")
    endif()
    if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WIN})
        set(TARGET_CPU_ARCHITECTURE "x64")
    endif()
endif()
`,
        cxxCfgs,
        cxxFlags_Msvc, cxxFlags_Gnu,
    ))

    for idx, _ := range cxxCfgsDebug {
        WriteWithIndent(builder, 0, "if(USING_MSVC)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), cxxFlags_Debug_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), lnkSharedFlags_Debug_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), lnkExecFlags_Debug_Msvc,
            ))
        WriteWithIndent(builder, 4, "endif()\n")

        WriteWithIndent(builder, 0, "if(USING_MINIMAL)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), cxxFlags_Debug_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), lnkSharedFlags_Debug_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDebug[idx]), lnkExecFlags_Debug_Gnu,
            ))
        WriteWithIndent(builder, 0, "endif()\n")

        continue
    }

    for idx, _ := range cxxCfgsDevelopment {
        WriteWithIndent(builder, 0, "if(USING_MSVC)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), cxxFlags_Development_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), lnkSharedFlags_Development_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), lnkExecFlags_Development_Msvc,
            ))
        WriteWithIndent(builder, 0, "endif()\n")

        WriteWithIndent(builder, 0, "if(USING_MINIMAL)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), cxxFlags_Development_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), lnkSharedFlags_Development_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), lnkExecFlags_Development_Gnu,
            ))
        WriteWithIndent(builder, 0, "endif()\n")

        continue
    }

    for idx, _ := range cxxCfgsShipping {
        WriteWithIndent(builder, 0, "if(USING_MSVC)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), cxxFlags_Shipping_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), lnkSharedFlags_Shipping_Msvc,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), lnkExecFlags_Shipping_Msvc,
            ))
        WriteWithIndent(builder, 0, "endif()\n")

        WriteWithIndent(builder, 0, "if(USING_MINIMAL)\n")
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), cxxFlags_Shipping_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), lnkSharedFlags_Shipping_Gnu,
            ))
        WriteWithIndent(builder, 4, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgsShipping[idx]), lnkExecFlags_Shipping_Gnu,
            ))
        WriteWithIndent(builder, 0, "endif()\n")

        continue
    }

    WriteWithIndent(builder, 0, "message(STATUS \"Using CXX_FLAGS: [${CMAKE_CXX_FLAGS}].\")\n")
    WriteWithIndent(builder, 0, "message(STATUS \"Using SHARED_LNK_FLAGS: [${CMAKE_SHARED_LINKER_FLAGS}].\")\n")
    WriteWithIndent(builder, 0, "message(STATUS \"Using EXE_LNK_FLAGS: [${CMAKE_EXE_LINKER_FLAGS}].\")\n")
    for idx, _ := range cxxCfgsDebug {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using CXX_FLAGS_%s: [${CMAKE_CXX_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDebug[idx]), strings.ToUpper(cxxCfgsDebug[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using SHARED_LNK_FLAGS_%s: [${CMAKE_SHARED_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDebug[idx]), strings.ToUpper(cxxCfgsDebug[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using EXE_LNK_FLAGS_%s: [${CMAKE_EXE_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDebug[idx]), strings.ToUpper(cxxCfgsDebug[idx]),
            ))
    }
    for idx, _ := range cxxCfgsDevelopment {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using CXX_FLAGS_%s: [${CMAKE_CXX_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), strings.ToUpper(cxxCfgsDevelopment[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using SHARED_LNK_FLAGS_%s: [${CMAKE_SHARED_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), strings.ToUpper(cxxCfgsDevelopment[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using EXE_LNK_FLAGS_%s: [${CMAKE_EXE_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsDevelopment[idx]), strings.ToUpper(cxxCfgsDevelopment[idx]),
            ))
    }
    for idx, _ := range cxxCfgsShipping {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using CXX_FLAGS_%s: [${CMAKE_CXX_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsShipping[idx]), strings.ToUpper(cxxCfgsShipping[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using SHARED_LNK_FLAGS_%s: [${CMAKE_SHARED_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsShipping[idx]), strings.ToUpper(cxxCfgsShipping[idx]),
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "message(STATUS \"Using EXE_LNK_FLAGS_%s: [${CMAKE_EXE_LINKER_FLAGS_%s}].\")\n",
            strings.ToUpper(cxxCfgsShipping[idx]), strings.ToUpper(cxxCfgsShipping[idx]),
            ))
    }

    return
}

func WriteCmakeFileProjectSpecificSections(builder *strings.Builder) {
    if builder == nil {
        panic("WriteCmakeFileProjectSpecificSections called with nil builder.")
    }

    for idx, _ := range Shared.GApp.Projects {
        var project *Shared.Project = &Shared.GApp.Projects[idx]
        WriteCmakeFileForSpecificProject(builder, 0, project)
    }

    return
}

func WriteCmakeFileForSpecificProject(builder *strings.Builder, indent int, project *Shared.Project) {
    if builder == nil {
        panic("WriteCmakeFileForSpecificProject called with nil builder.")
    }
    if project == nil {
        panic("WriteCmakeFileForSpecificProject called with nil project.")
    }

    for idx, _ := range project.Modules {
        var module *Shared.Module = &project.Modules[idx]
        WriteCmakeFileForSpecificModule(builder, indent, module)
    }

    return
}

func GetAllUniqueBuildConfigurations() []string {
    var out []string = []string{}
    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        out = append(out, fmt.Sprintf("Debug-%s", targ.GetSuffix()))
        out = append(out, fmt.Sprintf("Development-%s", targ.GetSuffix()))
        out = append(out, fmt.Sprintf("Shipping-%s", targ.GetSuffix()))

        continue
    }

    return out
}

func GetAllUniqueDebugBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Debug") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetAllUniqueDevelopmentBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Development") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetAllUniqueShippingBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Shipping") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetRelativeDirForCoreAfx() string {
    return fmt.Sprintf("%s/Source/Public/CoreAfx.h", Shared.GApp.GetCheckedModuleByName("Lal").GetRelativeModuleDir())
}

func WriteCmakeFileForSpecificModule(builder *strings.Builder, indent int, module *Shared.Module) {
    type FileFlags struct {
        file string
        fileFlags string
    }

    if builder == nil {
        panic("WriteCmakeFileForSpecificModule called with nil builder.")
    }
    if module == nil {
        panic("WriteCmakeFileForSpecificModule called with nil module.")
    }

    WriteWithIndent(builder, indent, "\n")
    WriteWithIndent(builder, indent, "############################\n")
    WriteWithIndent(builder, indent, fmt.Sprintf("# Module: %s\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "############################\n")

    var cDefines []string
    var cDefines_Msvc []string /* Not just cmp flags but also cond-cmp flags - as they will be rawly defined in cmake. */
    var cDefines_Minimal []string
    cDefines = append(cDefines, fmt.Sprintf("CURRENT_PROJECT_NAME=\"%s\"", module.Parent.Name))
    cDefines = append(cDefines, fmt.Sprintf("CURRENT_MODULE_NAME=\"%s\"", module.GetUsableName()))
    cDefines = append(cDefines, fmt.Sprintf("PRIVATE_JAFG_CURRENT_MODULE_PREPROC_IDENT=%s", module.GetPreProcIntAsString()))
    cDefines_Msvc = append(cDefines_Msvc, "$<$<STREQUAL:${TARGET_PLATFORM},${TARGET_PLATFORM_WIN}>:PLATFORM_WINDOWS>")
    cDefines_Msvc = append(cDefines_Msvc, "$<$<STREQUAL:${TARGET_PLATFORM},${TARGET_PLATFORM_WIN}>:PLATFORM_WINDOWS_WITH_MSVC>")
    cDefines_Msvc = append(cDefines_Msvc, "$<$<STREQUAL:${TARGET_PLATFORM},${TARGET_PLATFORM_WASM}>:PLATFORM_WASM>")
    cDefines_Minimal = append(cDefines_Minimal, fmt.Sprintf(`if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WIN})
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE
            PLATFORM_WINDOWS
            PLATFORM_WINDOWS_WITH_GNU
            )
    endif()`))
    cDefines_Minimal = append(cDefines_Minimal, fmt.Sprintf(`if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE
            PLATFORM_WASM
            )
        endif()`))
    var cDefines_Debug []string = []string{"IN_DEBUG=1"}
    var cDefines_Development []string = []string{"IN_DEVELOPMENT=1"}
    var cDefines_Shipping []string = []string{"IN_SHIPPING=1"}

    // Msvc only:
    var cxxPrivateFlags []string
    var cxxPrivateFileFlags []FileFlags
    if module.Pch.IsUse() {
        //cxxPrivateFlags = append(cxxPrivateFlags, "/YuCoreAfx.h")
        //cxxPrivateFileFlags = append(cxxPrivateFileFlags, FileFlags{
        //    fmt.Sprintf("%s%s", module.GetUsableName(), Shared.GeneratedTranslationsExtension),
        //    fmt.Sprintf("/YcCoreAfx.h")},
        //)
    }

    var publicIncludeDirs_AllTargets []string // For all generators.
    var publicIncludeDirs_AllTargets_Msvc []string
    var publicIncludeDirs_AllTargets_Minimal []string
    var privateIncludeDirs_AllTargets []string // For all generators.
    var privateIncludeDirs_AllTargets_Msvc []string
    var privateIncludeDirs_AllTargets_Minimal []string
    var publicLinkedLibs_AllTargets []string // For all generators.
    var publicLinkedLibs_AllTargets_Msvc []string
    var publicLinkedLibs_AllTargets_Minimal []string
    var publicLinkedLibs_AllTargets_Minimal_Formatted []string
    var privateLinkedLibs_AllTargets []string // For all generators.
    var privateLinkedLibs_AllTargets_Msvc []string
    var privateLinkedLibs_AllTargets_Minimal []string
    var privateLinkedLibs_AllTargets_Minimal_Formatted []string

    if module.GetUsableName() == "Engine" {
        privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, `if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WIN})
        target_link_libraries(${CUR_MOD_NAME} PRIVATE
            "SetupApi.lib"
            )
    endif()`,
        )
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_MOD_NAME \"%s\")\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_MOD_REL_PATH \"%s\")\n", module.GetRelativeModuleDir()))
    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_PROJ_REL_PATH \"%s\")\n", module.Parent.GetRelativeProjectDir()))

    WriteWithIndent(builder, indent, fmt.Sprintf("message(STATUS \"Adding module ${CUR_MOD_NAME}...\")\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf(`if(USING_MSVC)
%s    file(GLOB_RECURSE %s_SRC_FILES
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/**.md"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/**.jafgmod"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.h"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.hpp"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.c"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.cpp"
%s        )
%s    foreach(CUR_SRC_FILE ${%s_SRC_FILES})
%s        file(RELATIVE_PATH CUR_SRC_FILE_REL "${CMAKE_SOURCE_DIR}/%s" ${CUR_SRC_FILE})
%s        get_filename_component(CUR_FILE_DIR ${CUR_SRC_FILE_REL} PATH)
%s        if("${CUR_FILE_DIR}" STREQUAL "")
%s          set(MULTI_GEN_FILTER "")
%s        else()
%s          string(REPLACE "/" "\\" MULTI_GEN_FILTER ${CUR_FILE_DIR})
%s        endif()
%s        source_group("${MULTI_GEN_FILTER}" FILES ${CUR_SRC_FILE})
%s    endforeach()
%sendif()
%sif(USING_MINIMAL)
%s    file(GLOB_RECURSE %s_SRC_FILES
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.h"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.hpp"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.c"
%s        "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.cpp"
%s        )
%sendif()
`,
        Shared.Indent(indent), module.GetUsableName(),
        Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent),
        module.GetUsableName(),
        Shared.Indent(indent), module.GetRelativeModuleDir(),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), module.GetUsableName(),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
    ))

    WriteWithIndent(builder, indent, fmt.Sprintf(`file(GLOB_RECURSE %s_GEN_SRC_FILES
%s    "${CMAKE_SOURCE_DIR}/%s/**.h"
%s    "${CMAKE_SOURCE_DIR}/%s/**.hpp"
%s    "${CMAKE_SOURCE_DIR}/%s/**.c"
%s    "${CMAKE_SOURCE_DIR}/%s/**.cpp"
%s    )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("source_group(\"Generated Translation\" FILES ${%s_GEN_SRC_FILES})\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf(`file(GLOB_RECURSE %s_MISC_FILES
%s        "${CMAKE_SOURCE_DIR}/${CUR_PROJ_REL_PATH}/*.md"
%s        "${CMAKE_SOURCE_DIR}/${CUR_PROJ_REL_PATH}/*.jsfgproj"
%s        )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("source_group(\"\" FILES ${%s_MISC_FILES})\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+4, fmt.Sprintf(`file(GLOB_RECURSE %s_GEN_H_FILES
%s        "${CMAKE_SOURCE_DIR}/%s/**.h"
%s        "${CMAKE_SOURCE_DIR}/%s/**.hpp"
%s        )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.GetRelativeGeneratedHeaderDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedHeaderDirForModule(module),
        Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("source_group(\"Generated Headers\" FILES ${%s_GEN_H_FILES})\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set(%s_MISC_FILES \"\")\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set(%s_GEN_H_FILES \"\")\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, fmt.Sprintf("file(GLOB_RECURSE %s_C_SRC_FILES ${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.c)\n", module.GetUsableName()))

    if module.Kind.IsLaunch() {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "add_executable(${CUR_MOD_NAME} ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})\n",
            module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsShared() {
        WriteWithIndent(builder, indent, fmt.Sprintf(`if(COMPILER_SUPPORTS_SHARED_LNK)
    add_library(${CUR_MOD_NAME} SHARED ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})
else()
    add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})
endif()
`,
            module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
            module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsStatic() {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})\n",
            module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsInherit() {
        if module.Parent.DefaultKind.IsLaunch() {
            WriteWithIndent(builder, indent, fmt.Sprintf(
                "add_executable(${CUR_MOD_NAME} ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})\n",
                module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
            ))
        } else if module.Parent.DefaultKind.IsShared() {
            WriteWithIndent(builder, indent, fmt.Sprintf(`if(COMPILER_SUPPORTS_SHARED_LNK)
    add_library(${CUR_MOD_NAME} SHARED ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})
else()
    add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})
endif()
`,
                module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
                module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
                module.GetUsableName(), module.GetUsableName(),
            ))
        } else if module.Parent.DefaultKind.IsStatic() {
            WriteWithIndent(builder, indent, fmt.Sprintf(
                "add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_GEN_H_FILES} ${%s_MISC_FILES})\n",
                module.GetUsableName(), module.GetUsableName(), module.GetUsableName(), module.GetUsableName(),
            ))
        } else {
            panic(fmt.Sprintf("Unknown module kind: %d", module.Parent.DefaultKind))
        }
    } else {
        panic(fmt.Sprintf("Unknown module kind: %d", module.Kind))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("foreach(src_file ${%s_C_SRC_FILES})\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set_source_files_properties(${src_file} PROPERTIES LANGUAGE C)\n"))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set_source_files_properties(${src_file} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf("endforeach()\n"))

    if module.GetUsableName() == "Runtime" { /* Lol, this is hardcoded but will we ever change this :). */
        WriteWithIndent(builder, indent, "set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${CUR_MOD_NAME})\n")
    }

    if module.Kind.IsLaunch() || (module.Kind.IsInherit() && module.Parent.DefaultKind.IsLaunch()) {
        WriteWithIndent(builder, indent, fmt.Sprintf(`if(USING_MSVC)
%s    set_target_properties(${CUR_MOD_NAME} PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS")
%sendif()
%sif(USING_MINIMAL)
%s    if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WIN})
%s        set_target_properties(${CUR_MOD_NAME} PROPERTIES LINK_FLAGS "-mwindows")
%s    endif()
%s    if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
%s        set_target_properties(${CUR_MOD_NAME} PROPERTIES
%s            LINK_FLAGS "--shell-file ${CMAKE_SOURCE_DIR}/Content/Wasm/MinimalShell.html"
%s            SUFFIX ".html"
%s            )
%s    endif()
%sendif()
`,
            Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
            Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
            Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
            Shared.Indent(indent),
        ))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf(`if(USING_MINIMAL)
%s    if(${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
%s        target_compile_definitions(${CUR_MOD_NAME} PRIVATE PLATFORM_USES_WEBGL_TWO JAFG_NO_GLAD USE_FREETYPE=1)
%s        set_target_properties(${CUR_MOD_NAME} PROPERTIES
%s            LINK_FLAGS "-s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s USE_FREETYPE=1"
%s            )
%s    endif()
%sendif()
`,
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
    ))

    for idx, _ := range cxxPrivateFlags {
        WriteWithIndent(builder, indent, fmt.Sprintf("target_compile_options(${CUR_MOD_NAME} PRIVATE %s)\n", cxxPrivateFlags[idx]))
    }

    for idx, _ := range cxxPrivateFileFlags {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "set_source_files_properties(%s PROPERTIES COMPILE_FLAGS \"%s\")\n",
            cxxPrivateFileFlags[idx].file, cxxPrivateFileFlags[idx].fileFlags,
            ))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("set_target_properties(${CUR_MOD_NAME} PROPERTIES LINKER_LANGUAGE CXX)\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf("set_target_properties(${CUR_MOD_NAME} PROPERTIES FOLDER \"%s\")\n", module.Parent.GetRelativeProjectDir()))

    if module.Pch.IsUse() {
        WriteWithIndent(builder, indent, fmt.Sprintf("target_precompile_headers(${CUR_MOD_NAME} PRIVATE %s)\n", GetRelativeDirForCoreAfx()))
    }

    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_custom_command(TARGET ${CUR_MOD_NAME} PRE_BUILD\n"+
        "%s        COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\"\n"+
        "%s            --fwd --BuildTool --pre-build --BUILD_CONFIG=$<CONFIG> --PLATFORM=${TARGET_PLATFORM} --MOD_NAME=${CUR_MOD_NAME}\n"+
        "%s            --CFG_KIND=%s --CFG_SYSTEM=${TARGET_PLATFORM} --CFG_ARCHITECTURE=${TARGET_CPU_ARCHITECTURE}\n%s    )\n",
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        module.Kind.ToLuaString(&module.Parent.DefaultKind), Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_custom_command(TARGET ${CUR_MOD_NAME} POST_BUILD\n"+
        "%s        COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\"\n"+
        "%s            --fwd --BuildTool --post-build --BUILD_CONFIG=$<CONFIG> --PLATFORM=${TARGET_PLATFORM} --MOD_NAME=${CUR_MOD_NAME}\n"+
        "%s            --CFG_KIND=%s --CFG_SYSTEM=${TARGET_PLATFORM} --CFG_ARCHITECTURE=${TARGET_CPU_ARCHITECTURE}\n%s    )\n",
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        module.Kind.ToLuaString(&module.Parent.DefaultKind), Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_custom_target(pre_build_command_%s\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+8, fmt.Sprintf("COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\"\n"+
        "            --fwd --BuildTool --pre-build --BUILD_CONFIG=$<CONFIG> --PLATFORM=${TARGET_PLATFORM} --MOD_NAME=${CUR_MOD_NAME}\n"+
        "            --CFG_KIND=%s --CFG_SYSTEM=${TARGET_PLATFORM} --CFG_ARCHITECTURE=${TARGET_CPU_ARCHITECTURE}\n"+
        "        COMMENT \"Pre-build command for module %s\"\n",
        module.Kind.ToLuaString(&module.Parent.DefaultKind), module.GetUsableName(),
    ))
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_custom_target(post_build_command_%s\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+8, fmt.Sprintf("COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\"\n"+
        "            --fwd --BuildTool --post-build --BUILD_CONFIG=$<CONFIG> --PLATFORM=${TARGET_PLATFORM} --MOD_NAME=${CUR_MOD_NAME}\n"+
        "            --CFG_KIND=%s --CFG_SYSTEM=${TARGET_PLATFORM} --CFG_ARCHITECTURE=${TARGET_CPU_ARCHITECTURE}\n"+
        "        COMMENT \"Post-build command for module %s.\"\n",
        module.Kind.ToLuaString(&module.Parent.DefaultKind), module.GetUsableName(),
        ))
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_dependencies(${CUR_MOD_NAME} pre_build_command_%s)\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("add_dependencies(${CUR_MOD_NAME} post_build_command_%s)\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "endif()\n")

    /* Always include ourselves. */
    publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/Public\""))
    publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.GeneratedHeadersDir))

    for _, dep := range module.PublicDependencies {
        if dep == "CORE_DEPENDENCIES" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.VendorIncludeDir))
            continue
        }
        if dep == "RHI_DEPENDENCIES" {
            /* Has to be included directly and not inside the namespace. */
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Freetype\"", Shared.VendorIncludeDir))
            publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        target_link_libraries(${CUR_MOD_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/%s/libfreetype.dll.a")
    endif()`,
                Shared.VendorLibDir,
            ))
            publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/freetype.lib\"", Shared.VendorLibDir))
            publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        target_link_libraries(${CUR_MOD_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/%s/libglfw3.a")
    endif()`,
                Shared.VendorLibDir,
            ))
            publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/glfw3.lib\"", Shared.VendorLibDir))
            continue
        }

        var modDep *Shared.Module = Shared.GApp.GetCheckedModuleByName(dep)
        publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf(
            "\"${CMAKE_SOURCE_DIR}/%s/Source/Public\"",
            modDep.GetRelativeModuleDir(),
        ))
        publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, modDep.GetUsableName())

        /*
         * Special case for the tester module. We should not hard-code this but use the mod config file.
         * But this works for now. Just a short-term solution.
         */
        if module.GetUsableName() == "Tester" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets,
                fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Source\"",
                    modDep.GetRelativeModuleDir()))
        }

        continue
    }

    for _, dep := range module.PrivateDependencies {
        if dep == "CORE_DEPENDENCIES" {
            privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.VendorIncludeDir))
            continue
        }
        if dep == "RHI_DEPENDENCIES" {
            /* Has to be included directly and not inside the namespace. */
            privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Freetype\"", Shared.VendorIncludeDir))
            privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        target_link_libraries(${CUR_MOD_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/%s/libfreetype.dll.a")
    endif()`,
                Shared.VendorLibDir,
            ))
            privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/freetype.lib\"", Shared.VendorLibDir))
            privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        target_link_libraries(${CUR_MOD_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/%s/libglfw3.a")
    endif()`,
                Shared.VendorLibDir,
            ))
            privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/glfw3.lib\"", Shared.VendorLibDir))
            continue
        }

        var modDep *Shared.Module = Shared.GApp.GetCheckedModuleByName(dep)

        privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf(
            "\"${CMAKE_SOURCE_DIR}/%s/Source/Public\"",
            modDep.GetRelativeModuleDir(),
        ))
        privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, modDep.GetUsableName())

        /*
         * Special case for the tester module. We should not hard-code this but use the mod config file.
         * But this works for now. Just a short-term solution.
         */
        if module.GetUsableName() == "Tester" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets,
                fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Source\"",
                    modDep.GetRelativeModuleDir()))
        }

        continue
    }

    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        /* Lol, in cmake you cannot define a different folder for intermediates
           haha wtf?? We fix this in the post-run call. */
        WriteWithIndent(builder, indent, fmt.Sprintf(`set_target_properties(${CUR_MOD_NAME} PROPERTIES
%s    ARCHIVE_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    ARCHIVE_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Development-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Development-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Development-%s/${CUR_MOD_REL_PATH}"
%s    ARCHIVE_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${TARGET_PLATFORM}-${TARGET_CPU_ARCHITECTURE}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    )
`,
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent),
        ))

        var publicIncludeDirs []string
        var publicLinkedLibs []string

        /* Libs only in debug / development. */
        var publicLinkedDebugLibs []string
        var privateLinkedDebugLibs []string
        var publicLinkedDebugLibs_Msvc []string
        var privateLinkedDebugLibs_Msvc []string
        var publicLinkedDebugLibs_Minimal []string
        var privateLinkedDebugLibs_Minimal []string

        /* Libs only in shipping. */
        var publicLinkedShippingLibs []string
        var privateLinkedShippingLibs []string
        var publicLinkedShippingLibs_Msvc []string
        var privateLinkedShippingLibs_Msvc []string
        var publicLinkedShippingLibs_Minimal []string
        var privateLinkedShippingLibs_Minimal []string

        for _, addcDef := range targ.AdditionalDefines {
            cDefines_Msvc = append(cDefines_Msvc, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>", targ.GetSuffix(), addcDef))
            cDefines_Msvc = append(cDefines_Msvc, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>", targ.GetSuffix(), addcDef))
            cDefines_Msvc = append(cDefines_Msvc, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>", targ.GetSuffix(), addcDef))
            cDefines_Minimal = append(cDefines_Minimal, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), addcDef))
            cDefines_Minimal = append(cDefines_Minimal, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), addcDef))
            cDefines_Minimal = append(cDefines_Minimal, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), addcDef))
            continue
        }

        for _, dep := range module.PublicDependencies {
            if dep == "CORE_DEPENDENCIES" {
                publicLinkedDebugLibs_Msvc = append(publicLinkedDebugLibs_Msvc, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.lib", Shared.VendorLibDir))
                publicLinkedShippingLibs_Msvc = append(publicLinkedShippingLibs_Msvc, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.lib", Shared.VendorLibDir))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
            target_link_libraries(${CUR_MOD_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/%s/libFastNoiseD.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
            target_link_libraries(${CUR_MOD_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/%s/libFastNoiseD.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
            target_link_libraries(${CUR_MOD_NAME} PUBLIC "${CMAKE_SOURCE_DIR}/%s/libFastNoise.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                continue
            }
            if dep == "RHI_DEPENDENCIES" {
                continue
            }
            continue
        }

        for _, dep := range module.PrivateDependencies {
            if dep == "CORE_DEPENDENCIES" {
                privateLinkedDebugLibs_Msvc = append(privateLinkedDebugLibs_Msvc, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.lib", Shared.VendorLibDir))
                privateLinkedShippingLibs_Msvc = append(privateLinkedShippingLibs_Msvc, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.lib", Shared.VendorLibDir))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
            target_link_libraries(${CUR_MOD_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/%s/libFastNoiseD.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
            target_link_libraries(${CUR_MOD_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/%s/libFastNoiseD.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(`if(NOT ${TARGET_PLATFORM} STREQUAL ${TARGET_PLATFORM_WASM})
        if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
            target_link_libraries(${CUR_MOD_NAME} PRIVATE "${CMAKE_SOURCE_DIR}/%s/libFastNoise.dll.a")
        endif()
    endif()`,
                    targ.GetSuffix(), Shared.VendorLibDir,
                ))
                continue
            }
            if dep == "RHI_DEPENDENCIES" {
                continue
            }
            continue
        }

        for _, condInc := range module.ConditionalPublicDependencies {
            if condInc.IsConditionTrue(targ) {
                var modCondInc *Shared.Module = Shared.GApp.GetCheckedModuleByName(condInc.Include)
                if !slices.Contains(publicIncludeDirs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/Source/Public", modCondInc.GetRelativeModuleDir())) {
                    publicIncludeDirs = append(publicIncludeDirs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/Source/Public", modCondInc.GetRelativeModuleDir()))
                }
                if !slices.Contains(publicLinkedLibs, modCondInc.GetUsableName()) {
                    publicLinkedLibs = append(publicLinkedLibs, modCondInc.GetUsableName())
                }
            }
            continue
        }

        if len(publicIncludeDirs) > 0 {
            for _, inc := range publicIncludeDirs {
                publicIncludeDirs_AllTargets_Msvc = append(publicIncludeDirs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
                publicIncludeDirs_AllTargets_Msvc = append(publicIncludeDirs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
                publicIncludeDirs_AllTargets_Msvc = append(publicIncludeDirs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
                publicIncludeDirs_AllTargets_Minimal = append(publicIncludeDirs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_include_directories(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), inc))
                publicIncludeDirs_AllTargets_Minimal = append(publicIncludeDirs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_include_directories(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), inc))
                publicIncludeDirs_AllTargets_Minimal = append(publicIncludeDirs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_include_directories(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), inc))
                continue
            }
        }
        if len(publicLinkedLibs) > 0 {
            for _, lib := range publicLinkedLibs {
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }

        if len(publicLinkedDebugLibs) > 0 {
            for _, lib := range publicLinkedDebugLibs {
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }
        if len(publicLinkedDebugLibs_Msvc) > 0 {
            for _, lib := range publicLinkedDebugLibs_Msvc {
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                continue
            }
        }
        if len(publicLinkedDebugLibs_Minimal) > 0 {
            for _, lib := range publicLinkedDebugLibs_Minimal {
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }

        if len(privateLinkedDebugLibs) > 0 {
            for _, lib := range privateLinkedDebugLibs {
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }
        if len(privateLinkedDebugLibs_Msvc) > 0 {
            for _, lib := range privateLinkedDebugLibs_Msvc {
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                continue
            }
        }
        if len(privateLinkedDebugLibs_Minimal) > 0 {
            for _, lib := range privateLinkedDebugLibs_Minimal {
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Debug-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Development-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }

        if len(publicLinkedShippingLibs) > 0 {
            for _, lib := range publicLinkedShippingLibs {
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }
        if len(privateLinkedShippingLibs_Msvc) > 0 {
            for _, lib := range privateLinkedShippingLibs_Msvc {
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                continue
            }
        }
        if len(privateLinkedShippingLibs_Minimal) > 0 {
            for _, lib := range privateLinkedShippingLibs_Minimal {
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }

        if len(privateLinkedShippingLibs) > 0 {
            for _, lib := range privateLinkedShippingLibs {
                privateLinkedLibs_AllTargets_Msvc = append(privateLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                privateLinkedLibs_AllTargets_Minimal = append(privateLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_link_libraries(${CUR_MOD_NAME} PRIVATE %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }
        if len(publicLinkedShippingLibs_Msvc) > 0 {
            for _, lib := range publicLinkedShippingLibs_Msvc {
                publicLinkedLibs_AllTargets_Msvc = append(publicLinkedLibs_AllTargets_Msvc, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                continue
            }
        }
        if len(publicLinkedShippingLibs_Minimal) > 0 {
            for _, lib := range publicLinkedShippingLibs_Minimal {
                publicLinkedLibs_AllTargets_Minimal = append(publicLinkedLibs_AllTargets_Minimal, fmt.Sprintf(
`if(${CMAKE_BUILD_TYPE} STREQUAL "Shipping-%s")
        target_link_libraries(${CUR_MOD_NAME} PUBLIC %s)
    endif()`, targ.GetSuffix(), lib))
                continue
            }
        }

        continue
    }

    WriteWithIndent(builder, indent, "target_include_directories(${CUR_MOD_NAME} PUBLIC\n")
    for incIdx, _ := range publicIncludeDirs_AllTargets {
        WriteWithIndent(builder, indent+4, publicIncludeDirs_AllTargets[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, "target_include_directories(${CUR_MOD_NAME} PUBLIC\n")
    for incIdx, _ := range publicIncludeDirs_AllTargets_Msvc {
        WriteWithIndent(builder, indent+8, publicIncludeDirs_AllTargets_Msvc[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    for incIdx, _ := range publicIncludeDirs_AllTargets_Minimal {
        WriteWithIndent(builder, indent+4, publicIncludeDirs_AllTargets_Minimal[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "target_include_directories(${CUR_MOD_NAME} PRIVATE\n")
    for incIdx, _ := range privateIncludeDirs_AllTargets {
        WriteWithIndent(builder, indent+4, privateIncludeDirs_AllTargets[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, "target_include_directories(${CUR_MOD_NAME} PRIVATE\n")
    for incIdx, _ := range privateIncludeDirs_AllTargets_Msvc {
        WriteWithIndent(builder, indent+8, privateIncludeDirs_AllTargets_Msvc[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    for incIdx, _ := range privateIncludeDirs_AllTargets_Minimal {
        WriteWithIndent(builder, indent+4, privateIncludeDirs_AllTargets_Minimal[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "target_link_libraries(${CUR_MOD_NAME} PUBLIC\n")
    for libIdx, _ := range publicLinkedLibs_AllTargets {
        WriteWithIndent(builder, indent+4, publicLinkedLibs_AllTargets[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, "target_link_libraries(${CUR_MOD_NAME} PUBLIC\n")
    for libIdx, _ := range publicLinkedLibs_AllTargets_Msvc {
        WriteWithIndent(builder, indent+8, publicLinkedLibs_AllTargets_Msvc[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    WriteWithIndent(builder, indent+4, "target_link_libraries(${CUR_MOD_NAME} PUBLIC\n")
    for libIdx, _ := range publicLinkedLibs_AllTargets_Minimal_Formatted {
        WriteWithIndent(builder, indent+8, publicLinkedLibs_AllTargets_Minimal_Formatted[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    for libIdx, _ := range publicLinkedLibs_AllTargets_Minimal {
        WriteWithIndent(builder, indent+4, publicLinkedLibs_AllTargets_Minimal[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "target_link_libraries(${CUR_MOD_NAME} PRIVATE\n")
    for libIdx, _ := range privateLinkedLibs_AllTargets {
        WriteWithIndent(builder, indent+4, privateLinkedLibs_AllTargets[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, "target_link_libraries(${CUR_MOD_NAME} PRIVATE\n")
    for libIdx, _ := range privateLinkedLibs_AllTargets_Msvc {
        WriteWithIndent(builder, indent+8, privateLinkedLibs_AllTargets_Msvc[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent, "endif()\n")
    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    WriteWithIndent(builder, indent+4, "target_link_libraries(${CUR_MOD_NAME} PRIVATE\n")
    for libIdx, _ := range privateLinkedLibs_AllTargets_Minimal_Formatted {
        WriteWithIndent(builder, indent+8, privateLinkedLibs_AllTargets_Minimal_Formatted[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+8, ")\n")
    for libIdx, _ := range privateLinkedLibs_AllTargets_Minimal {
        WriteWithIndent(builder, indent+4, privateLinkedLibs_AllTargets_Minimal[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "target_compile_definitions(${CUR_MOD_NAME} PRIVATE\n")
    for defIdx, _ := range cDefines {
        WriteWithIndent(builder, indent+4, fmt.Sprintf("%s\n", cDefines[defIdx]))
        continue
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "if(USING_MSVC)\n")
    WriteWithIndent(builder, indent+4, "target_compile_definitions(${CUR_MOD_NAME} PRIVATE\n")
    for defIdx, _ := range cDefines_Msvc {
        WriteWithIndent(builder, indent+8, fmt.Sprintf("%s\n", cDefines_Msvc[defIdx]))
        continue
    }
    for defIdx, _ := range cDefines_Debug {
        for _, debugCfg := range GetAllUniqueDebugBuildConfigurations() {
            WriteWithIndent(builder, indent+8, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
                debugCfg, cDefines_Debug[defIdx],
            ))
            continue
        }
        continue
    }
    for defIdx, _ := range cDefines_Development {
        for _, developmentCfg := range GetAllUniqueDevelopmentBuildConfigurations() {
            WriteWithIndent(builder, indent+8, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
                developmentCfg, cDefines_Development[defIdx],
            ))
            continue
        }
        continue
    }
    for defIdx, _ := range cDefines_Shipping {
        for _, shippingCfg := range GetAllUniqueShippingBuildConfigurations() {
            WriteWithIndent(builder, indent+8, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
                shippingCfg, cDefines_Shipping[defIdx],
            ))
            continue
        }
        continue
    }
    WriteWithIndent(builder, indent+8, ")\n")
    WriteWithIndent(builder, indent, "endif()\n")

    WriteWithIndent(builder, indent, "if(USING_MINIMAL)\n")
    for defIdx, _ := range cDefines_Debug {
        for _, debugCfg := range GetAllUniqueDebugBuildConfigurations() {
            WriteWithIndent(builder, indent+4, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()
`, debugCfg, cDefines_Debug[defIdx]))
        }
    }
    for defIdx, _ := range cDefines_Development {
        for _, developmentCfg := range GetAllUniqueDevelopmentBuildConfigurations() {
            WriteWithIndent(builder, indent+4, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()
`,
                developmentCfg, cDefines_Development[defIdx],
            ))
        }
    }
    for defIdx, _ := range cDefines_Shipping {
        for _, shippingCfg := range GetAllUniqueShippingBuildConfigurations() {
            WriteWithIndent(builder, indent+4, fmt.Sprintf(`if(${CMAKE_BUILD_TYPE} STREQUAL "%s")
        target_compile_definitions(${CUR_MOD_NAME} PRIVATE %s)
    endif()
`,
                shippingCfg, cDefines_Shipping[defIdx],
            ))
        }
    }
    for defIdx, _ := range cDefines_Minimal {
        WriteWithIndent(builder, indent+4, fmt.Sprintf("%s\n", cDefines_Minimal[defIdx]))
        continue
    }
    WriteWithIndent(builder, indent, "endif()\n")

    return
}

func WriteCmakeFileGeneratedSection(builder *strings.Builder) {
    // Currently not used.
    return
}

func WriteCmakeFileVendorSection(builder *strings.Builder) {
    // This is absolutely hard-coded but who gives.
    WriteWithIndent(builder, 0, "\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "# Vendor\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "file(GLOB_RECURSE Vendor_SRC_FILES\n")
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.md\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.jafgmod\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.jafgproj\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.h\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.hpp\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.c\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.cpp\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 0, ")\n")
    WriteWithIndent(builder, 0, "source_group(\"Vendor\" FILES ${Vendor_SRC_FILES})\n")
    WriteWithIndent(builder, 0, "add_custom_target(Vendor SOURCES ${Vendor_SRC_FILES})\n")
    WriteWithIndent(builder, 0, "set_target_properties(Vendor PROPERTIES FOLDER \"Vendor\")\n")

    return
}

func AddCustomCmakeWasmRuntime(builder *strings.Builder) {
    WriteWithIndent(builder, 0, "\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "# Wasm runtime\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "if(USING_MSVC)\n")
    WriteWithIndent(builder, 4, "add_custom_command(\n")
    WriteWithIndent(builder, 8, "OUTPUT ${CMAKE_BINARY_DIR}/Internal/WasmRuntime.stamp\n")
    WriteWithIndent(builder, 8, "COMMAND ${CMAKE_COMMAND} -E echo \"Running WasmRuntime with build config $<CONFIG>.\"\n")
    WriteWithIndent(builder, 8, "COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_BINARY_DIR}/Internal/WasmRuntime.stamp\n")
    WriteWithIndent(builder, 8, "COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\"\n")
    WriteWithIndent(builder, 12, "--custom-command --WasmRuntime --BUILD_CONFIG=$<CONFIG> --PLATFORM=${TARGET_PLATFORM}\n")
    WriteWithIndent(builder, 8, ")\n")
    WriteWithIndent(builder, 4, "add_custom_target(WasmRuntime\n")
    WriteWithIndent(builder, 8, "COMMAND ${CMAKE_COMMAND} -E echo \"Running WasmRuntime with build config $<CONFIG>.\"\n")
    WriteWithIndent(builder, 8, "DEPENDS ${CMAKE_BINARY_DIR}/Internal/WasmRuntime.stamp\n")
    WriteWithIndent(builder, 8, ")\n")
    WriteWithIndent(builder, 4, "set_target_properties(\"WasmRuntime\" PROPERTIES FOLDER \"Internal\")\n")
    WriteWithIndent(builder, 0, "endif()\n")

    return
}

type CmakeConfigurePresetCacheVariable struct {
    Name string
    Value string
}

func (variable *CmakeConfigurePresetCacheVariable) ToJson(indent int, builder *strings.Builder) {
    if builder == nil {
        panic("builder is nil")
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("\"%s\": \"%s\"", variable.Name, variable.Value))

    return
}

type CmakeConfigurePreset struct {
    Name string
    FriendlyName string
    Generator string
    CacheVariables []CmakeConfigurePresetCacheVariable
}

func (preset *CmakeConfigurePreset) ToJson(builder *strings.Builder) {
    if builder == nil {
        panic("builder is nil")
    }

    WriteWithIndent(builder, 8, "{\n")
    WriteWithIndent(builder, 12, fmt.Sprintf("\"name\": \"%s\",\n", preset.Name))
    WriteWithIndent(builder, 12, fmt.Sprintf("\"displayName\": \"%s\",\n", preset.FriendlyName))
    WriteWithIndent(builder, 12, fmt.Sprintf("\"generator\": \"%s\",\n", preset.Generator))
    WriteWithIndent(builder, 12, "\"cacheVariables\": {\n")
    for idx, _ := range preset.CacheVariables {
        preset.CacheVariables[idx].ToJson(16, builder)
        if idx < len(preset.CacheVariables) - 1 {
            builder.WriteString(",")
        }
        builder.WriteString("\n")
    }
    WriteWithIndent(builder, 12, "}\n")
    WriteWithIndent(builder, 8, "}")

    return
}

type CmakeBuildPreset struct {
    Name string
    FriendlyName string
    Configuration string
    ConfigurationPreset string
}

func (preset *CmakeBuildPreset) ToJson(builder *strings.Builder) {
    if builder == nil {
        panic("builder is nil")
    }

    WriteWithIndent(builder, 8, "{\n")
    WriteWithIndent(builder, 12, fmt.Sprintf("\"name\": \"%s\",\n", preset.Name))
    WriteWithIndent(builder, 12, fmt.Sprintf("\"displayName\": \"%s\",\n", preset.FriendlyName))
    WriteWithIndent(builder, 12, fmt.Sprintf("\"configuration\": \"%s\",\n", preset.Configuration))
    WriteWithIndent(builder, 12, fmt.Sprintf("\"configurePreset\": \"%s\"\n", preset.ConfigurationPreset))
    WriteWithIndent(builder, 8, "}")

    return
}

func WriteCmakePresetsFileBody(file *os.File) {
    var builder *strings.Builder = &strings.Builder{}

    WriteWithIndent(builder, 0, "{\n")
    WriteWithIndent(builder, 4, "\"version\": 3,\n")

    WriteWithIndent(builder, 4, "\"configurePresets\": [\n")
    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        GenerateConfigurationPreset(builder, "Windows GNU", "Debug", targ.GetSuffix())
        builder.WriteString(",\n")
        GenerateConfigurationPreset(builder, "Windows GNU", "Development", targ.GetSuffix())
        builder.WriteString(",\n")
        GenerateConfigurationPreset(builder, "Windows GNU", "Shipping", targ.GetSuffix())
        builder.WriteString(",\n")
        GenerateConfigurationPreset(builder, "Wasm GNU", "Debug", targ.GetSuffix())
        builder.WriteString(",\n")
        GenerateConfigurationPreset(builder, "Wasm GNU", "Development", targ.GetSuffix())
        builder.WriteString(",\n")
        GenerateConfigurationPreset(builder, "Wasm GNU", "Shipping", targ.GetSuffix())

        if idx < len(targs) - 1 {
            builder.WriteString(",\n")
        }

        continue
    }
    WriteWithIndent(builder, 0, "\n    ]\n")

    //WriteWithIndent(builder, 0, ",\n")
    //WriteWithIndent(builder, 4, "\"buildPresets\": [\n")
    //var W_DebugClient CmakeBuildPreset = CmakeBuildPreset{
    //    Name: "Debug-Client",
    //    FriendlyName: "Debug-Client",
    //    Configuration: "Debug-Client",
    //    ConfigurationPreset: "windows-gnu",
    //}
    //W_DebugClient.ToJson(builder)
    //WriteWithIndent(builder, 0, "\n    ]\n")

    WriteWithIndent(builder, 0, "}\n")

    Shared.WriteToFile(file, builder.String())
    return

}

func GenerateConfigurationPreset(builder *strings.Builder, platform string, buildType string, targetSuffix string) {
    var realPlatform string = platform
    if strings.Contains(platform, " ") {
        realPlatform = platform[:strings.Index(platform, " ")]
    }

    var WindowsPreset CmakeConfigurePreset = CmakeConfigurePreset{
        Name: fmt.Sprintf("%s-%s-%s", strings.ToLower(strings.ReplaceAll(platform, " ", "-")), strings.ToLower(buildType), strings.ToLower(targetSuffix)),
        FriendlyName: fmt.Sprintf("%s | %s-%s", platform, buildType, targetSuffix),
        Generator: "MinGW Makefiles",
        CacheVariables: []CmakeConfigurePresetCacheVariable{
            CmakeConfigurePresetCacheVariable{
                Name: "TARGET_PLATFORM",
                Value: realPlatform,
            },
            CmakeConfigurePresetCacheVariable{
                Name: "CMAKE_BUILD_TYPE",
                Value: fmt.Sprintf("%s-%s", buildType, targetSuffix),
            },
        },
    }
    WindowsPreset.ToJson(builder)

    return
}
