// Copyright 2024 mzoesch. All rights reserved.

package SolutionGenerator

import (
    "Jafg/Shared"
    "fmt"
    "os"
    "slices"
    "strings"
)

func GenerateCmakeSolution() {
    var handle *os.File = PrepareCmakeFile()
    WriteCmakeFileBody(handle)

    Shared.CloseFile(handle)

    return
}

func PrepareCmakeFile() *os.File {
    fmt.Println("Preparing CMakeLists.txt file...")

    Shared.CheckRelativeFile(Shared.SolutionCmakeFile)

    var file *os.File = Shared.OpenRelativeFile(Shared.SolutionCmakeFile, true, os.O_RDWR)

    Shared.WriteToFile(
        file,
        "# Copyright 2024 mzoesch. All rights reserved.\n"+
            "# This file is automatically generated by Jafg and can be deleted with no fear.\n\n",
    )

    return file
}

func WriteCmakeFileBody(handle *os.File) {
    if handle == nil {
        panic("WriteCmakeFileBody called with nil handle.")
    }

    var builder strings.Builder = strings.Builder{}

    WriteAllCmakeFileSharedLogic(&builder)
    WriteCmakeFileProjectSpecificSections(&builder)
    WriteCmakeFileGeneratedSection(&builder)
    WriteCmakeFileVendorSection(&builder)

    Shared.WriteToFile(handle, builder.String())

    return
}

func WriteAllCmakeFileSharedLogic(builder *strings.Builder) {
    WriteWithIndent(builder, 0, "cmake_minimum_required(VERSION 3.19...3.30)\n")
    WriteWithIndent(builder, 0, "if (${CMAKE_VERSION} VERSION_LESS 3.12)\n")
    WriteWithIndent(builder, 4, "cmake_policy(VERSION ${CMAKE_VERSION})\n")
    WriteWithIndent(builder, 0, "endif()\n")
    WriteWithIndent(builder, 0, "find_package(Python REQUIRED COMPONENTS Interpreter)\n")
    WriteWithIndent(builder, 0, "message(STATUS \"Python_EXECUTABLE: ${Python_EXECUTABLE}\")\n")
    WriteWithIndent(builder, 0, "set(CMAKE_CXX_STANDARD 20)\n")
    WriteWithIndent(builder, 0, "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n")
    WriteWithIndent(builder, 0, "set(CMAKE_CXX_EXTENSIONS OFF)\n")
    WriteWithIndent(builder, 0, "project(\n")
    WriteWithIndent(builder, 4, "Jafg\n")
    WriteWithIndent(builder, 4, "VERSION 0.0.1\n") /* Make this dynamic with the already currently used config file. */
    WriteWithIndent(builder, 4, "DESCRIPTION \"S-Jafg\"\n")
    WriteWithIndent(builder, 4, "LANGUAGES CXX\n")
    WriteWithIndent(builder, 0, "    )\n")

    var cxxCfgDebug []string
    var cxxCfgDevelopment []string
    var cxxCfgShipping []string

    var cxxFlags string = "/GR-" // gcc/clang: -fno-rtti
    cxxFlags += " /Zc:__cplusplus" // msvc only!

    // gnu Flags: -Wall -Wextra -Wpedantic -g -O0 -02(DEV)
    var cxxFlags_Debug string = "/W3 /Zi /Od"
    var lnkSharedFlags_Debug string = "/DEBUG /NODEFAULTLIB:libcmt /NODEFAULTLIB:msvcrtd" //"-rdynamic" /* lnx */
    var lnkExecFlags_Debug string = "/DEBUG"

    var cxxFlags_Development string = "/W3 /Zi /O2" // /Wall for max warnings - but /W4 should be enough for msvc.
    var lnkSharedFlags_Development string = "/DEBUG /NODEFAULTLIB:libcmt /NODEFAULTLIB:msvcrtd" //"-rdynamic" /* lnx */
    var lnkExecFlags_Development string = "/DEBUG"

    /* Should we really use fast maths?? */
    // gnu Flags: -03 -ffast-math -flto -march=native
    var cxxFlags_Shipping string = "/fp:fast /Ox /GL"
    var lnkSharedFlags_Shipping string = "/LTCG /DEBUG:NONE" //"-flto"
    var lnkExecFlags_Shipping string = ""

    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        cxxCfgDebug = append(cxxCfgDebug, fmt.Sprintf("Debug-%s", targ.GetSuffix()))
        cxxCfgDevelopment = append(cxxCfgDevelopment, fmt.Sprintf("Development-%s", targ.GetSuffix()))
        cxxCfgShipping = append(cxxCfgShipping, fmt.Sprintf("Shipping-%s", targ.GetSuffix()))

        continue
    }

    if len(cxxCfgDebug) == 0 {
        panic("No targets found in cfg debug.")
    }
    if len(cxxCfgDevelopment) == 0 {
        panic("No targets found in cfg development.")
    }
    if len(cxxCfgShipping) == 0 {
        panic("No targets found in cfg shipping.")
    }

    var cxxCfgs string = ""
    for idx, _ := range cxxCfgDebug {
        cxxCfgs += cxxCfgDebug[idx]
        cxxCfgs += ";"
    }
    for idx, _ := range cxxCfgDevelopment {
        cxxCfgs += cxxCfgDevelopment[idx]
        cxxCfgs += ";"
    }
    for idx, _ := range cxxCfgShipping {
        cxxCfgs += cxxCfgShipping[idx]
        if idx < len(cxxCfgShipping)-1 {
            cxxCfgs += ";"
        }
    }
    WriteWithIndent(builder, 0,
        fmt.Sprintf(
            "set(CMAKE_CONFIGURATION_TYPES\n    \"%s\"\n    CACHE STRING \"Limited configurations.\" FORCE\n    )\n",
            cxxCfgs,
        ))

    WriteWithIndent(builder, 0, fmt.Sprintf(
        "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} %s\")\n",
        cxxFlags,
        ))

    for idx, _ := range cxxCfgDebug {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDebug[idx]), cxxFlags_Debug,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDebug[idx]), lnkSharedFlags_Debug,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a debug target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDebug[idx]), lnkExecFlags_Debug,
            ))

        continue
    }

    for idx, _ := range cxxCfgDevelopment {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDevelopment[idx]), cxxFlags_Development,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDevelopment[idx]), lnkSharedFlags_Development,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a development target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgDevelopment[idx]), lnkExecFlags_Development,
            ))

        continue
    }

    for idx, _ := range cxxCfgShipping {
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_CXX_FLAGS_%s \"%s\" CACHE STRING \"Flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgShipping[idx]), cxxFlags_Shipping,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_SHARED_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgShipping[idx]), lnkSharedFlags_Shipping,
            ))
        WriteWithIndent(builder, 0, fmt.Sprintf(
            "set(CMAKE_EXE_LINKER_FLAGS_%s \"%s\" CACHE STRING \"Linker flags for a shipping target configuration.\" FORCE)\n",
            strings.ToUpper(cxxCfgShipping[idx]), lnkExecFlags_Shipping,
            ))

        continue
    }

    return
}

func WriteCmakeFileProjectSpecificSections(builder *strings.Builder) {
    if builder == nil {
        panic("WriteCmakeFileProjectSpecificSections called with nil builder.")
    }

    for idx, _ := range Shared.GApp.Projects {
        var project *Shared.Project = &Shared.GApp.Projects[idx]
        WriteCmakeFileForSpecificProject(builder, 0, project)
    }

    return
}

func WriteCmakeFileForSpecificProject(builder *strings.Builder, indent int, project *Shared.Project) {
    if builder == nil {
        panic("WriteCmakeFileForSpecificProject called with nil builder.")
    }
    if project == nil {
        panic("WriteCmakeFileForSpecificProject called with nil project.")
    }

    for idx, _ := range project.Modules {
        var module *Shared.Module = &project.Modules[idx]
        WriteCmakeFileForSpecificModule(builder, indent, module)
    }

    return
}

func GetAllUniqueBuildConfigurations() []string {
    var out []string = []string{}
    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        out = append(out, fmt.Sprintf("Debug-%s", targ.GetSuffix()))
        out = append(out, fmt.Sprintf("Development-%s", targ.GetSuffix()))
        out = append(out, fmt.Sprintf("Shipping-%s", targ.GetSuffix()))

        continue
    }

    return out
}

func GetAllUniqueDebugBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Debug") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetAllUniqueDevelopmentBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Development") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetAllUniqueShippingBuildConfigurations() []string {
    var out []string = []string{}

    for _, targ := range GetAllUniqueBuildConfigurations() {
        if strings.Contains(targ, "Shipping") {
            out = append(out, targ)
        }

        continue
    }

    return out
}

func GetRelativeDirForCoreAfx() string {
    return fmt.Sprintf("%s/Source/Public/CoreAfx.h", Shared.GApp.GetCheckedModuleByName("Lal").GetRelativeModuleDir())
}

func WriteCmakeFileForSpecificModule(builder *strings.Builder, indent int, module *Shared.Module) {
    type FileFlags struct {
        file string
        fileFlags string
    }

    if builder == nil {
        panic("WriteCmakeFileForSpecificModule called with nil builder.")
    }
    if module == nil {
        panic("WriteCmakeFileForSpecificModule called with nil module.")
    }

    WriteWithIndent(builder, indent, "\n")
    WriteWithIndent(builder, indent, "############################\n")
    WriteWithIndent(builder, indent, fmt.Sprintf("# Module: %s\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, "############################\n")

    var cDefines []string /* Not just cmp flags but also cond-cmp flags - as they will be rawly defined in cmake. */
    cDefines = append(cDefines, fmt.Sprintf("CURRENT_PROJECT_NAME=\"%s\"", module.Parent.Name))
    cDefines = append(cDefines, fmt.Sprintf("CURRENT_MODULE_NAME=\"%s\"", module.GetUsableName()))
    cDefines = append(cDefines, fmt.Sprintf("PRIVATE_JAFG_CURRENT_MODULE_PREPROC_IDENT=%s", module.GetPreProcIntAsString()))
    cDefines = append(cDefines, fmt.Sprintf("$<$<STREQUAL:$<PLATFORM_ID>,Windows>:PLATFORM_WINDOWS>"))
    var cDefines_Debug       []string = []string{ "IN_DEBUG=1" }
    var cDefines_Development []string = []string{ "IN_DEVELOPMENT=1" }
    var cDefines_Shipping    []string = []string{ "IN_SHIPPING=1" }

    // Msvc only:
    var cxxPrivateFlags []string
    var cxxPrivateFileFlags []FileFlags
    if module.Pch.IsUse() {
        //cxxPrivateFlags = append(cxxPrivateFlags, "/YuCoreAfx.h")
        //cxxPrivateFileFlags = append(cxxPrivateFileFlags, FileFlags{
        //    fmt.Sprintf("%s%s", module.GetUsableName(), Shared.GeneratedTranslationsExtension),
        //    fmt.Sprintf("/YcCoreAfx.h")},
        //)
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_MOD_NAME \"%s\")\n", module.GetUsableName()))
    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_MOD_REL_PATH \"%s\")\n", module.GetRelativeModuleDir()))
    WriteWithIndent(builder, indent, fmt.Sprintf("set(CUR_PROJ_REL_PATH \"%s\")\n", module.Parent.GetRelativeProjectDir()))

    WriteWithIndent(builder, indent, fmt.Sprintf("message(STATUS \"Adding module ${CUR_MOD_NAME}...\")\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf(`file(GLOB_RECURSE %s_SRC_FILES
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/**.md"
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/**.jafgmod"
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.h"
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.hpp"
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.c"
%s    "${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.cpp"
%s    )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent, fmt.Sprintf(`foreach(CUR_SRC_FILE ${%s_SRC_FILES})
%s    file(RELATIVE_PATH CUR_SRC_FILE_REL "${CMAKE_SOURCE_DIR}/%s" ${CUR_SRC_FILE})
%s    get_filename_component(CUR_FILE_DIR ${CUR_SRC_FILE_REL} PATH)
%s    if("${CUR_FILE_DIR}" STREQUAL "")
%s      set(MULTI_GEN_FILTER "")
%s    else()
%s      string(REPLACE "/" "\\" MULTI_GEN_FILTER ${CUR_FILE_DIR})
%s    endif()
%s    source_group("${MULTI_GEN_FILTER}" FILES ${CUR_SRC_FILE})
%sendforeach()
`,
        module.GetUsableName(),
        Shared.Indent(indent), module.GetRelativeModuleDir(),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
    ))

    WriteWithIndent(builder, indent, fmt.Sprintf(`file(GLOB_RECURSE %s_GEN_SRC_FILES
%s    "${CMAKE_SOURCE_DIR}/%s/**.h"
%s    "${CMAKE_SOURCE_DIR}/%s/**.hpp"
%s    "${CMAKE_SOURCE_DIR}/%s/**.c"
%s    "${CMAKE_SOURCE_DIR}/%s/**.cpp"
%s    )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent), Shared.GetRelativeGeneratedTranslationDirForModule(module),
        Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent, fmt.Sprintf("source_group(\"Generated Translation\" FILES ${%s_GEN_SRC_FILES})\n", module.GetUsableName()))

    WriteWithIndent(builder, indent, fmt.Sprintf(`file(GLOB_RECURSE %s_MISC_FILES
%s    "${CMAKE_SOURCE_DIR}/${CUR_PROJ_REL_PATH}/*.md"
%s    "${CMAKE_SOURCE_DIR}/${CUR_PROJ_REL_PATH}/*.jsfgproj"
%s    )
`,
        module.GetUsableName(),
        Shared.Indent(indent), Shared.Indent(indent), Shared.Indent(indent),
    ))
    WriteWithIndent(builder, indent, fmt.Sprintf("source_group(\"\" FILES ${%s_MISC_FILES})\n", module.GetUsableName()))

    WriteWithIndent(builder, indent, fmt.Sprintf("file(GLOB_RECURSE %s_C_SRC_FILES ${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/*.c)\n", module.GetUsableName()))

    if module.Kind.IsLaunch() {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "add_executable(${CUR_MOD_NAME} ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
            module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsShared() {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "add_library(${CUR_MOD_NAME} SHARED ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
            module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsStatic() {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
            module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
        ))
    } else if module.Kind.IsInherit() {
        if module.Parent.DefaultKind.IsLaunch() {
            WriteWithIndent(builder, indent, fmt.Sprintf(
                "add_executable(${CUR_MOD_NAME} ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
                module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
            ))
        } else if module.Parent.DefaultKind.IsShared() {
            WriteWithIndent(builder, indent, fmt.Sprintf(
                "add_library(${CUR_MOD_NAME} SHARED ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
                module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
            ))
        } else if module.Parent.DefaultKind.IsStatic() {
            WriteWithIndent(builder, indent, fmt.Sprintf(
                "add_library(${CUR_MOD_NAME} STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_MISC_FILES})\n",
                module.GetUsableName(),module.GetUsableName(), module.GetUsableName(),
            ))
        } else {
            panic(fmt.Sprintf("Unknown module kind: %d", module.Parent.DefaultKind))
        }
    } else {
        panic(fmt.Sprintf("Unknown module kind: %d", module.Kind))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("foreach(src_file ${%s_C_SRC_FILES})\n", module.GetUsableName()))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set_source_files_properties(${src_file} PROPERTIES LANGUAGE C)\n"))
    WriteWithIndent(builder, indent+4, fmt.Sprintf("set_source_files_properties(${src_file} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf("endforeach()\n"))

    if module.GetUsableName() == "Runtime" { /* Lol, this is hardcoded but will we ever change this :). */
        WriteWithIndent(builder, indent, "set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${CUR_MOD_NAME})\n")
    }

    if module.Kind.IsLaunch() || (module.Kind.IsInherit() && module.Parent.DefaultKind.IsLaunch()) {
        WriteWithIndent(builder, indent, fmt.Sprintf("set_target_properties(${CUR_MOD_NAME} PROPERTIES LINK_FLAGS \"/SUBSYSTEM:WINDOWS\")\n"))
    }

    for idx, _ := range cxxPrivateFlags {
        WriteWithIndent(builder, indent, fmt.Sprintf("target_compile_options(${CUR_MOD_NAME} PRIVATE %s)\n", cxxPrivateFlags[idx]))
    }

    for idx, _ := range cxxPrivateFileFlags {
        WriteWithIndent(builder, indent, fmt.Sprintf(
            "set_source_files_properties(%s PROPERTIES COMPILE_FLAGS \"%s\")\n",
            cxxPrivateFileFlags[idx].file, cxxPrivateFileFlags[idx].fileFlags,
            ))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("set_target_properties(${CUR_MOD_NAME} PROPERTIES LINKER_LANGUAGE CXX)\n"))
    WriteWithIndent(builder, indent, fmt.Sprintf("set_target_properties(${CUR_MOD_NAME} PROPERTIES FOLDER \"%s\")\n", module.Parent.GetRelativeProjectDir()))

    if module.Pch.IsUse() {
       WriteWithIndent(builder, indent, fmt.Sprintf("target_precompile_headers(${CUR_MOD_NAME} PRIVATE %s)\n", GetRelativeDirForCoreAfx()))
    }

    WriteWithIndent(builder, indent, fmt.Sprintf("add_custom_command(TARGET ${CUR_MOD_NAME} PRE_BUILD\n"+
        "%s    COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\" --fwd --BuildTool --pre-build "+
        "--BUILD_CONFIG=$<CONFIG> --PLATFORM=$<PLATFORM_ID> --MOD_NAME=${CUR_MOD_NAME} --CFG_KIND=%s\n "+
        "--CFG_SYSTEM=$<PLATFORM_ID> --CFG_ARCHITECTURE=${CMAKE_SYSTEM_PROCESSOR}\n%s    )\n",
        Shared.Indent(indent), module.Kind.ToLuaString(&module.Parent.DefaultKind), Shared.Indent(indent),
    ))

    WriteWithIndent(builder, indent, fmt.Sprintf("add_custom_command(TARGET ${CUR_MOD_NAME} POST_BUILD\n"+
        "%s    COMMAND ${Python_EXECUTABLE} \"${CMAKE_SOURCE_DIR}/Program.py\" --fwd --BuildTool --post-build "+
        "--BUILD_CONFIG=$<CONFIG> --PLATFORM=$<PLATFORM_ID> --MOD_NAME=${CUR_MOD_NAME} --CFG_KIND=%s\n "+
        "--CFG_SYSTEM=$<PLATFORM_ID> --CFG_ARCHITECTURE=${CMAKE_SYSTEM_PROCESSOR}\n%s    )\n",
        Shared.Indent(indent), module.Kind.ToLuaString(&module.Parent.DefaultKind), Shared.Indent(indent),
    ))

    var publicIncludeDirs_AllTargets []string
    var privateIncludeDirs_AllTargets []string
    var publicLinkedLibs_AllTargets []string
    var privateLinkedLibs_AllTargets []string

    /* Always include ourselves. */
    publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/${CUR_MOD_REL_PATH}/Source/Public\""))
    publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.GeneratedHeadersDir))

    for _, dep := range module.PublicDependencies {
        if dep == "CORE_DEPENDENCIES" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.VendorIncludeDir))
            continue
        }
        if dep == "RHI_DEPENDENCIES" {
            /* Has to be included directly and not inside the namespace. */
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Freetype\"", Shared.VendorIncludeDir))
            publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/freetype.lib", Shared.VendorLibDir))
            publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/glfw3.lib", Shared.VendorLibDir))
            continue
        }

        var modDep *Shared.Module = Shared.GApp.GetCheckedModuleByName(dep)
        publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf(
            "\"${CMAKE_SOURCE_DIR}/%s/Source/Public\"",
            modDep.GetRelativeModuleDir(),
        ))
        publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, modDep.GetUsableName())

        /*
         * Special case for the tester module. We should not hard-code this but use the mod config file.
         * But this works for now. Just a short-term solution.
         */
        if module.GetUsableName() == "Tester" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets,
                fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Source\"",
                    modDep.GetRelativeModuleDir()))
        }

        continue
    }

    for _, dep := range module.PrivateDependencies {
        if dep == "CORE_DEPENDENCIES" {
            privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s\"", Shared.VendorIncludeDir))
            continue
        }
        if dep == "RHI_DEPENDENCIES" {
            /* Has to be included directly and not inside the namespace. */
            privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Freetype\"", Shared.VendorIncludeDir))
            privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/freetype.lib\"", Shared.VendorLibDir))
            privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/glfw3.lib\"", Shared.VendorLibDir))
            continue
        }

        var modDep *Shared.Module = Shared.GApp.GetCheckedModuleByName(dep)

        privateIncludeDirs_AllTargets = append(privateIncludeDirs_AllTargets, fmt.Sprintf(
            "\"${CMAKE_SOURCE_DIR}/%s/Source/Public\"",
            modDep.GetRelativeModuleDir(),
        ))
        privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, modDep.GetUsableName())

        /*
         * Special case for the tester module. We should not hard-code this but use the mod config file.
         * But this works for now. Just a short-term solution.
         */
        if module.GetUsableName() == "Tester" {
            publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets,
                fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/Source\"",
                    modDep.GetRelativeModuleDir()))
        }

        continue
    }

    var targs []Shared.Target = Shared.GApp.GetAllUniqueTargets()
    for idx, _ := range targs {
        var targ *Shared.Target = &targs[idx]

        /* Lol, in cmake you cannot define a different folder for intermediates
           haha wtf?? We fix this in the post-run call. */
        WriteWithIndent(builder, indent, fmt.Sprintf(`set_target_properties(${CUR_MOD_NAME} PROPERTIES
%s    ARCHIVE_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_DEBUG-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Debug-%s/${CUR_MOD_REL_PATH}"
%s    ARCHIVE_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Development-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Development-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_DEVELOPMENT-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Development-%s/${CUR_MOD_REL_PATH}"
%s    ARCHIVE_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    LIBRARY_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    RUNTIME_OUTPUT_DIRECTORY_SHIPPING-%s "${CMAKE_SOURCE_DIR}/Binaries/${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}/Shipping-%s/${CUR_MOD_REL_PATH}"
%s    )
`,
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent), strings.ToUpper(targ.GetSuffix()), targ.GetSuffix(),
            Shared.Indent(indent),
        ))

        var publicIncludeDirs []string
        var publicLinkedLibs []string

        /* Libs only in debug / development. */
        var publicLinkedDebugLibs []string
        var privateLinkedDebugLibs []string
        /* Libs only in shipping. */
        var publicLinkedShippingLibs []string
        var privateLinkedShippingLibs []string

        for _, addcDef := range targ.AdditionalDefines {
            cDefines = append(cDefines, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>", targ.GetSuffix(), addcDef))
            cDefines = append(cDefines, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>", targ.GetSuffix(), addcDef))
            cDefines = append(cDefines, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>", targ.GetSuffix(), addcDef))
            continue
        }

        for _, dep := range module.PublicDependencies {
            if dep == "CORE_DEPENDENCIES" {
                publicLinkedDebugLibs = append(publicLinkedDebugLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.lib", Shared.VendorLibDir))
                //publicLinkedDebugLibs = append(publicLinkedDebugLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.dll", Shared.VendorLibDir))
                publicLinkedShippingLibs = append(publicLinkedShippingLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.lib", Shared.VendorLibDir))
                //publicLinkedShippingLibs = append(publicLinkedShippingLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.dll", Shared.VendorLibDir))
                continue
            }
            if dep == "RHI_DEPENDENCIES" {
                continue
            }
            continue
        }

        for _, dep := range module.PrivateDependencies {
            if dep == "CORE_DEPENDENCIES" {
                privateLinkedDebugLibs = append(privateLinkedDebugLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.lib", Shared.VendorLibDir))
                //privateLinkedDebugLibs = append(privateLinkedDebugLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoiseD.dll", Shared.VendorLibDir))
                privateLinkedShippingLibs = append(privateLinkedShippingLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.lib", Shared.VendorLibDir))
                //privateLinkedShippingLibs = append(privateLinkedShippingLibs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/FastNoise.dll", Shared.VendorLibDir))
                continue
            }
            if dep == "RHI_DEPENDENCIES" {
                continue
            }
            continue
        }

        for _, condInc := range module.ConditionalPublicDependencies {
            if condInc.IsConditionTrue(targ) {
                var modCondInc *Shared.Module = Shared.GApp.GetCheckedModuleByName(condInc.Include)
                if !slices.Contains(publicIncludeDirs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/Source/Public", modCondInc.GetRelativeModuleDir())) {
                    publicIncludeDirs = append(publicIncludeDirs, fmt.Sprintf("${CMAKE_SOURCE_DIR}/%s/Source/Public", modCondInc.GetRelativeModuleDir()))
                }
                if !slices.Contains(publicLinkedLibs, modCondInc.GetUsableName()) {
                    publicLinkedLibs = append(publicLinkedLibs, modCondInc.GetUsableName())
                }
            }
            continue
        }

        if len(publicIncludeDirs) > 0 {
            for _, inc := range publicIncludeDirs {
                publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
                publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
                publicIncludeDirs_AllTargets = append(publicIncludeDirs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), inc,
                ))
            }
        }
        if len(publicLinkedLibs) > 0 {
            for _, lib := range publicLinkedLibs {
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
            }
        }

        if len(publicLinkedDebugLibs) > 0 {
            for _, lib := range publicLinkedDebugLibs {
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
            }
        }
        if len(privateLinkedDebugLibs) > 0 {
            for _, lib := range privateLinkedDebugLibs {
                privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Debug-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
                privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Development-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
            }
        }

        if len(publicLinkedShippingLibs) > 0 {
            for _, lib := range publicLinkedShippingLibs {
                publicLinkedLibs_AllTargets = append(publicLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
            }
        }
        if len(privateLinkedShippingLibs) > 0 {
            for _, lib := range privateLinkedShippingLibs {
                privateLinkedLibs_AllTargets = append(privateLinkedLibs_AllTargets, fmt.Sprintf(
                    "$<$<STREQUAL:$<CONFIG>,Shipping-%s>:%s>",
                    targ.GetSuffix(), lib,
                ))
            }
        }

        continue
    }

    WriteWithIndent(builder, indent, "target_include_directories(${CUR_MOD_NAME} PUBLIC\n")
    for incIdx, _ := range publicIncludeDirs_AllTargets {
        WriteWithIndent(builder, indent+4, publicIncludeDirs_AllTargets[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "target_include_directories(${CUR_MOD_NAME} PRIVATE\n")
    for incIdx, _ := range privateIncludeDirs_AllTargets {
        WriteWithIndent(builder, indent+4, privateIncludeDirs_AllTargets[incIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "target_link_libraries(${CUR_MOD_NAME} PUBLIC\n")
    for libIdx, _ := range publicLinkedLibs_AllTargets {
        WriteWithIndent(builder, indent+4, publicLinkedLibs_AllTargets[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")
    WriteWithIndent(builder, indent, "target_link_libraries(${CUR_MOD_NAME} PRIVATE\n")
    for libIdx, _ := range privateLinkedLibs_AllTargets {
        WriteWithIndent(builder, indent+4, privateLinkedLibs_AllTargets[libIdx]+"\n")
    }
    WriteWithIndent(builder, indent+4, ")\n")

    WriteWithIndent(builder, indent, "target_compile_definitions(${CUR_MOD_NAME} PRIVATE\n")
    for defIdx, _ := range cDefines {
        WriteWithIndent(builder, indent+4, fmt.Sprintf("%s\n", cDefines[defIdx]))
        continue
    }
    for defIdx, _ := range cDefines_Debug {
        for _, debugCfg := range GetAllUniqueDebugBuildConfigurations() {
            WriteWithIndent(builder, indent+4, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
                debugCfg, cDefines_Debug[defIdx],
            ))
            continue
        }
        continue
    }
    for defIdx, _ := range cDefines_Development {
      for _, developmentCfg := range GetAllUniqueDevelopmentBuildConfigurations() {
          WriteWithIndent(builder, indent+4, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
              developmentCfg, cDefines_Development[defIdx],
          ))
          continue
      }
      continue
    }
    for defIdx, _ := range cDefines_Shipping {
       for _, shippingCfg := range GetAllUniqueShippingBuildConfigurations() {
           WriteWithIndent(builder, indent+4, fmt.Sprintf("$<$<STREQUAL:$<CONFIG>,%s>:%s>\n",
               shippingCfg, cDefines_Shipping[defIdx],
           ))
           continue
       }
       continue
    }
    WriteWithIndent(builder, indent+4, ")\n")

    return
}

func WriteCmakeFileGeneratedSection(builder *strings.Builder) {
    // Currently not used.
    return
}

func WriteCmakeFileVendorSection(builder *strings.Builder) {
    // This is absolutely hard-coded but who gives.
    WriteWithIndent(builder, 0, "\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "# Vendor\n")
    WriteWithIndent(builder, 0, "############################\n")
    WriteWithIndent(builder, 0, "file(GLOB_RECURSE Vendor_SRC_FILES\n")
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.md\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.jafgmod\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.jafgproj\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.h\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.hpp\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.c\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 4, fmt.Sprintf("\"${CMAKE_SOURCE_DIR}/%s/**.cpp\"\n", Shared.VendorIncludeDir))
    WriteWithIndent(builder, 0, ")\n")
    WriteWithIndent(builder, 0, "source_group(\"Vendor\" FILES ${Vendor_SRC_FILES})\n")
    WriteWithIndent(builder, 0, "add_custom_target(Vendor SOURCES ${Vendor_SRC_FILES})\n")
    WriteWithIndent(builder, 0, "set_target_properties(Vendor PROPERTIES FOLDER \"Vendor\")\n")

    return
}
