// Copyright mzoesch. All rights reserved.

package SolutionGenerator

import (
    "Jafg/BuildTool"
    "Jafg/Core"
    "Jafg/Shared"
    "fmt"
    "strings"
)

type CmakeConfigurePresetCacheVariable struct {
    Name  string
    Value string
}

func (variable *CmakeConfigurePresetCacheVariable) ToJson(indent int, b *strings.Builder) {
    if b == nil {
        panic("builder is nil")
    }
    Wwinnl(b, indent, fmt.Sprintf("\"%s\": \"%s\"", variable.Name, variable.Value))
    return
}

type CmakeConfigurePresetEnvironment struct {
    Key   string
    Value string
}

type CmakeConfigurePreset struct {
    Name           string
    FriendlyName   string
    Generator      string
    BinaryDir      string
    CacheVariables []CmakeConfigurePresetCacheVariable
    Environment    []CmakeConfigurePresetEnvironment
}

func (preset *CmakeConfigurePreset) ToJson(b *strings.Builder) {
    if b == nil {
        panic("builder is nil")
    }

    Wwi(b, 2, "{")
    Wwi(b, 3, fmt.Sprintf("\"name\": \"%s\",", preset.Name))
    Wwi(b, 3, fmt.Sprintf("\"displayName\": \"%s\",", preset.FriendlyName))
    Wwi(b, 3, fmt.Sprintf("\"generator\": \"%s\",", preset.Generator))
    Wwi(b, 3, fmt.Sprintf("\"binaryDir\": \"%s\",", preset.BinaryDir))
    Wwi(b, 3, "\"cacheVariables\": {")
    for idx, _ := range preset.CacheVariables {
       preset.CacheVariables[idx].ToJson(4, b)
       if idx < len(preset.CacheVariables)-1 {
           Wni(b, ",")
       } else {
           Wni(b, "")
       }
    }
    Wwi(b, 3, "},")
    Wwi(b, 3, "\"environment\": {")
    for idx, _ := range preset.Environment {
        Wwinnl(b, 4, fmt.Sprintf("\"%s\": \"%s\"", preset.Environment[idx].Key, preset.Environment[idx].Value))
        if idx < len(preset.Environment)-1 {
            Wni(b, ",")
        } else {
            Wni(b, "")
        }
    }
    Wwi(b, 3, "}")
    Wwinnl(b, 2, "}")

    return
}

func MakeCmakeScripts(sln *Core.Solution, bEmulate bool) error {
    MakePchForAllModules(sln)

    var tActivateMsvc string = fmt.Sprintf("%s/%s", sln.GetSavedRelativeDir_CMake(), Core.FileName_ActivateMsvcBat)
    Shared.CheckRelativeFile(tActivateMsvc)

    var activateBuilder strings.Builder = strings.Builder{}
    var ab *strings.Builder = &activateBuilder
    Wni(ab, "@REM Copyright mzoesch. All rights reserved.")
    Wni(ab, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
    Wni(ab, "@REM This file activates the MSVC compiler for the current shell. Run this before doing windows builds with cmake.")
    Wni(ab, "")
    Wni(ab, "@echo off")
    Wni(ab, "")
    Wni(ab, Shared.ReadRelativeFile(fmt.Sprintf("%s/%s", Core.DirPath_ShellStubs, "MakeEnvForLatestMsvc.bat")))
    Wni(ab, "")
    Shared.OpenAndWriteToRelativeFileIfDifferent(tActivateMsvc, activateBuilder.String(), true)

    var platforms []string = []string{"Windows64", "Windows32FastWasm", "Wasm"}

    for _, t := range sln.Targets {
        var p string = "Windows64"

        var tDir = fmt.Sprintf("%s/%s/%s", sln.GetSavedRelativeDir_CMake(), p, t.Name)
        Shared.CheckRelativeDir(tDir)

        var tSetupBat string = fmt.Sprintf("%s/%s", tDir, Core.FileName_CmakeSetupBat)
        Shared.CheckRelativeFile(tSetupBat)
        var tNinjaBat string = fmt.Sprintf("%s/%s", tDir, Core.FileName_CmakeBuildBat)
        Shared.CheckRelativeFile(tNinjaBat)

        var builder strings.Builder = strings.Builder{}
        var b *strings.Builder = &builder
        Wni(b, "@REM Copyright mzoesch. All rights reserved.")
        Wni(b, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
        Wni(b, fmt.Sprintf("@REM This file generates the CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s].", sln.Name, p, t.Name))
        Wni(b, "")
        Wni(b, "@echo off")
        Wni(b, "")
        Wni(b, "set CURRENT_DIR=%cd%")
        Wni(b, "")
        Wni(b, Shared.ReadRelativeFile(fmt.Sprintf("%s/%s", Core.DirPath_ShellStubs, "MakeEnvForLatestMsvc.bat")))
        Wni(b, "")
        Wni(b, "cd /d %~dp0")
        Wni(b, "pushd ..")
        Wni(b, "pushd ..")
        Wni(b, "")
        Wni(b, fmt.Sprintf("echo Generating CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s] ...", sln.Name, p, t.Name))
        Wni(b, "echo Currently working in [%cd%].")
        Wni(b, "")
        Wni(b, fmt.Sprintf("cmake -S . -B \"%s\\%s\" -G Ninja -DTARGET_PLATFORM=%s -DTARGET_CONFIGURATION=%s -DCMAKE_C_COMPILER=\"%%MSVC_PATH%%\" -DCMAKE_CXX_COMPILER=\"%%MSVC_PATH%%\"", p, t.Name, p, t.Name))
        Wni(b, "")
        Wni(b, "popd")
        Wni(b, "popd")
        Wni(b, "cd /d %CURRENT_DIR%")
        Wni(b, "")
        Wni(b, "pause")
        Wni(b, "")
        Shared.OpenAndWriteToRelativeFileIfDifferent(tSetupBat, b.String(), true)

        builder = strings.Builder{}
        b = &builder
        Wni(b, "@REM Copyright mzoesch. All rights reserved.")
        Wni(b, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
        Wni(b, fmt.Sprintf("@REM This file builds the generated CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s].", sln.Name, p, t.Name))
        Wni(b, fmt.Sprintf("@REM You will have to run [%s] once before running this file.", Core.FileName_CmakeSetupBat))
        Wni(b, "")
        Wni(b, "@echo off")
        Wni(b, "")
        Wni(b, "if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )")
        Wni(b, "")
        Wni(b, "set CURRENT_DIR=%cd%")
        Wni(b, "")
        Wni(b, Shared.ReadRelativeFile(fmt.Sprintf("%s/%s", Core.DirPath_ShellStubs, "MakeEnvForLatestMsvc.bat")))
        Wni(b, "")
        Wni(b, "cd /d %~dp0")
        Wni(b, "")
        Wni(b, fmt.Sprintf("echo Building CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s] ...", sln.Name, p, t.Name))
        Wni(b, "")
        Wni(b, "ninja")
        Wni(b, "")
        Wni(b, "echo Currently working in [%cd%].")
        Wni(b, "cd /d %CURRENT_DIR%")
        Wni(b, "")
        Wni(b, "pause")
        Wni(b, "")
        Shared.OpenAndWriteToRelativeFileIfDifferent(tNinjaBat, b.String(), true)

        continue
    }

    for _, t := range sln.Targets {
        var p string = "Wasm"

        var tDir = fmt.Sprintf("%s/%s/%s", sln.GetSavedRelativeDir_CMake(), p, t.Name)
        Shared.CheckRelativeDir(tDir)

        var tSetupBat string = fmt.Sprintf("%s/%s", tDir, Core.FileName_CmakeSetupBat)
        Shared.CheckRelativeFile(tSetupBat)
        var tBuildBat string = fmt.Sprintf("%s/%s", tDir, Core.FileName_CmakeBuildBat)
        Shared.CheckRelativeFile(tBuildBat)
        var tCleanBuildBat string = fmt.Sprintf("%s/%s", tDir, Core.FileName_CmakeCleanBuildBat)
        Shared.CheckRelativeFile(tCleanBuildBat)

        var builder strings.Builder = strings.Builder{}
        var b *strings.Builder = &builder
        Wni(b, "@REM Copyright mzoesch. All rights reserved.")
        Wni(b, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
        Wni(b, fmt.Sprintf("@REM This file generates the CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s].", sln.Name, p, t.Name))
        Wni(b, "")
        Wni(b, "@echo off")
        Wni(b, "")
        Wni(b, "if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )")
        Wni(b, "")
        Wni(b, "set CURRENT_DIR=%cd%")
        Wni(b, "")
        Wni(b, "cd /d %~dp0")
        Wni(b, "pushd ..")
        Wni(b, "pushd ..")
        Wni(b, "")
        Wni(b, fmt.Sprintf("echo Generating CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s] ...", sln.Name, p, t.Name))
        Wni(b, "echo Currently working in [%cd%].")
        Wni(b, "")
        Wni(b, fmt.Sprintf("emcmake cmake -S . -B \"%s\\%s\" -G Ninja -DTARGET_PLATFORM=%s -DTARGET_CONFIGURATION=%s", p, t.Name, p, t.Name))
        Wni(b, "")
        Wni(b, "popd")
        Wni(b, "popd")
        Wni(b, "cd /d %CURRENT_DIR%")
        Wni(b, "")
        Wni(b, "pause")
        Wni(b, "")
        Shared.OpenAndWriteToRelativeFileIfDifferent(tSetupBat, b.String(), true)

        builder = strings.Builder{}
        b = &builder
        Wni(b, "@REM Copyright mzoesch. All rights reserved.")
        Wni(b, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
        Wni(b, fmt.Sprintf("@REM This file builds the generated CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s].", sln.Name, p, t.Name))
        Wni(b, fmt.Sprintf("@REM You will have to run [%s] once before running this file.", Core.FileName_CmakeSetupBat))
        Wni(b, "")
        Wni(b, "@echo off")
        Wni(b, "")
        Wni(b, "if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )")
        Wni(b, "")
        Wni(b, "cmake --build .")
        Wni(b, "")
        Wni(b, "pause")
        Wni(b, "")
        Shared.OpenAndWriteToRelativeFileIfDifferent(tBuildBat, b.String(), true)

        builder = strings.Builder{}
        b = &builder
        Wni(b, "@REM Copyright mzoesch. All rights reserved.")
        Wni(b, "@REM This file is automatically generated by Jafg and can be deleted with no fear.")
        Wni(b, fmt.Sprintf("@REM This file builds the generated CMake files for [Jafg-%s] on the platform [%s] with the build configuration [%s].", sln.Name, p, t.Name))
        Wni(b, fmt.Sprintf("@REM You will have to run [%s] once before running this file.", Core.FileName_CmakeSetupBat))
        Wni(b, "")
        Wni(b, "@echo off")
        Wni(b, "")
        Wni(b, "if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )")
        Wni(b, "")
        Wni(b, "cmake --build . --clean-first")
        Wni(b, "")
        Wni(b, "pause")
        Wni(b, "")
        Shared.OpenAndWriteToRelativeFileIfDifferent(tCleanBuildBat, b.String(), true)

        continue
    }

    err := MakeCmakeScript(sln)
    if err != nil {
        return err
    }

    if bEmulate {
        fmt.Printf("Emulating all compiler pre-build commands for solution [%s/%s] ...\n", sln.GetSavedRelativeDir_CMake(), sln.Name)
        for idxT, _ := range sln.Targets {
            var tar *Core.Target = &sln.Targets[idxT]
            for idxM, _ := range tar.Modules {
                var mod *Core.Module = &tar.Modules[idxM]

                var args []string = []string{
                    "pre-build", fmt.Sprintf("SLN=%s", sln.Name), fmt.Sprintf("MODULE=%s", mod.GetUniqueName()),
                    fmt.Sprintf("KIND=%s", mod.Kind.ToLuaString()), "ARCH=NOT_SET",
                    fmt.Sprintf("TARGET=%s", tar.Name), "PLATFORM=NOT_SET",
                }
                fmt.Printf(
                    "Emulating compiler pre-build commands for module [%s/%s] with args [%v] ...\n",
                    sln.GetSavedRelativeDir_CMake(), mod.Name, args,
                )
                BuildTool.Launch(args)
                continue
            }
            continue
        }
    }

    {
        var builder strings.Builder = strings.Builder{}
        var b *strings.Builder = &builder
        Wni(b, "{")
        Wwi(b, 1, "\"version\": 3,")
        Wwi(b, 1, "\"configurePresets\": [")

        for pidx, p := range platforms {
            for tidx, _ := range sln.Targets {
                var t *Core.Target = &sln.Targets[tidx]

                var ccompiler string
                var cxxcompiler string
                if p == "Windows64" {
                    ccompiler = "cl.exe"
                    cxxcompiler = "cl.exe"
                } else if p == "Windows32FastWasm" {
                    ccompiler = "gcc"
                    cxxcompiler = "g++"
                } else if p == "Wasm" {
                    ccompiler = "emcc"
                    cxxcompiler = "em++"
                }

                var preset CmakeConfigurePreset = CmakeConfigurePreset{
                    Name:         fmt.Sprintf("%s_%s", p, t.Name),
                    FriendlyName: fmt.Sprintf("%s | %s", p, t.Name),
                    Generator:    "Ninja",
                    BinaryDir:     fmt.Sprintf("%s/%s", p, t.Name),
                    CacheVariables: []CmakeConfigurePresetCacheVariable{
                        CmakeConfigurePresetCacheVariable{Name: "TARGET_PLATFORM", Value: p},
                        CmakeConfigurePresetCacheVariable{Name: "TARGET_CONFIGURATION", Value: t.Name},
                        CmakeConfigurePresetCacheVariable{Name: "CMAKE_C_COMPILER", Value: ccompiler},
                        CmakeConfigurePresetCacheVariable{Name: "CMAKE_CXX_COMPILER", Value: cxxcompiler},
                    },
                    Environment: []CmakeConfigurePresetEnvironment{
                        CmakeConfigurePresetEnvironment{Key: "VSCMD_START_DIR", Value: ""},
                        CmakeConfigurePresetEnvironment{Key: "VCVARS_BAT", Value: Core.FileName_ActivateMsvcBat},
                    },
                }
                preset.ToJson(b)

                if tidx < len(sln.Targets) - 1 {
                    Wni(b, ",")
                }
            }

            if pidx < len(platforms) - 1 {
                Wni(b, ",")
            } else {
                Wni(b, "")
            }
        }
        Wwi(b, 1, "],")
        Wwi(b, 1, "\"buildPresets\": [")
        for pidx, p := range platforms {
            for tidx, _ := range sln.Targets {
                var t *Core.Target = &sln.Targets[tidx]
                Wwi(b, 2, "{")
                Wwi(b, 3, fmt.Sprintf("\"name\": \"Build_%s_%s\",", p, t.Name))
                Wwi(b, 3, fmt.Sprintf("\"configurePreset\": \"%s_%s\"", p, t.Name))
                Wwinnl(b, 2, "}")
                if tidx < len(sln.Targets) - 1 {
                    Wni(b, ",")
                }
            }

            if pidx < len(platforms) - 1 {
                Wni(b, ",")
            } else {
                Wni(b, "")
            }
        }
        Wwi(b, 1, "]")
        Wni(b, "}")
        Shared.OpenAndWriteToRelativeFileIfDifferent(Core.MakeFilePath_CmakePresetsOut(sln), b.String(), true)
    }

    // generate ? but with what ninja, make, etc. This is maybe too user-specific, so just skip it??

    return nil
}

func MakeCmakeScript(sln *Core.Solution) error {
    fmt.Printf("Making CMake script for solution [%s/%s] ...\n", sln.GetSavedRelativeDir_CMake(), sln.Name)

    var fPath string = Core.MakeFilePath_CmakeOut(sln)
    Shared.CheckRelativeFile(fPath)

    var builder strings.Builder = strings.Builder{}
    var b *strings.Builder = &builder

    Wni(b, "# Copyright mzoesch. All rights reserved.")
    Wni(b, "# This file is automatically generated by Jafg and can be deleted with no fear.\n")

    Wni(b, "cmake_minimum_required(VERSION 3.21...3.30)")
    Wni(b, "if(${CMAKE_VERSION} VERSION_LESS 3.12)")
    Wwi(b, 1, "cmake_policy(VERSION ${CMAKE_VERSION})")
    Wni(b, "endif()")
    Wni(b, "find_package(Python REQUIRED COMPONENTS Interpreter)")
    Wni(b, "message(STATUS \"Python_EXECUTABLE: ${Python_EXECUTABLE}\")")
    Wni(b, "if(CMAKE_CONFIGURATION_TYPES)")
    Wwi(b, 1, "message(FATAL_ERROR \"Multi-configuration generators are not allowed. Please use a single-configuration generator with -G <generator>.\")")
    Wni(b, "endif()")
    Wni(b, "set(TARGET_PLATFORM_WIN \"Windows64\")")
    Wni(b, "set(TARGET_PLATFORM_WINGCC \"Windows32FastWasm\")")
    Wni(b, "set(TARGET_PLATFORM_WASM \"Wasm\")")
    Wni(b, "set(ALLOWED_TARGET_PLATFORMS ${TARGET_PLATFORM_WIN} ${TARGET_PLATFORM_WINGCC} ${TARGET_PLATFORM_WASM})")
    Wni(b, "if(NOT DEFINED TARGET_PLATFORM)")
    Wwi(b, 1, "message(FATAL_ERROR \"TARGET_PLATFORM is not defined. Please define it with -DTARGET_PLATFORM=<platform>. Allowed platforms are: ${ALLOWED_TARGET_PLATFORMS}.\")")
    Wni(b, "endif()")
    Wni(b, "list(FIND ALLOWED_TARGET_PLATFORMS ${TARGET_PLATFORM} TARGET_PLATFORM_INDEX)")
    Wni(b, "if(${TARGET_PLATFORM_INDEX} EQUAL -1)")
    Wwi(b, 1, "message(FATAL_ERROR \"TARGET_PLATFORM [${TARGET_PLATFORM}] is not valid. Please define it with -DTARGET_PLATFORM=<platform>. Allowed platforms are: ${ALLOWED_TARGET_PLATFORMS}.\")")
    Wni(b, "endif()")
    Wni(b, "message(STATUS \"TARGET_PLATFORM: ${TARGET_PLATFORM}\")")
    Wni(b, "set_property(CACHE TARGET_PLATFORM PROPERTY STRINGS ${ALLOWED_TARGET_PLATFORMS})")
    Wni(b, "set(ALLOWED_TARGET_CONFIGURATIONS)")
    Wni(b, "list(APPEND ALLOWED_TARGET_CONFIGURATIONS")
    for _, t := range sln.Targets {
        Wwi(b, 1, fmt.Sprintf("\"%s\"", t.Name))
    }
    Wni(b, ")")
    Wni(b, "if(NOT DEFINED TARGET_CONFIGURATION)")
    Wwi(b, 1, "message(FATAL_ERROR \"TARGET_CONFIGURATION is not defined. Please define it with -DTARGET_CONFIGURATION=<configuration>. Allowed configurations are: ${ALLOWED_TARGET_CONFIGURATIONS}.\")")
    Wni(b, "endif()")
    Wni(b, "list(FIND ALLOWED_TARGET_CONFIGURATIONS ${TARGET_CONFIGURATION} TARGET_CONFIGURATION_INDEX)")
    Wni(b, "if(${TARGET_CONFIGURATION_INDEX} EQUAL -1)")
    Wwi(b, 1, "message(FATAL_ERROR \"TARGET_CONFIGURATION [${TARGET_CONFIGURATION}] is not valid. Please define it with -DTARGET_CONFIGURATION=<configuration>. Allowed configurations are: ${ALLOWED_TARGET_CONFIGURATIONS}.\")")
    Wni(b, "endif()")
    Wni(b, "message(STATUS \"TARGET_CONFIGURATION: ${TARGET_CONFIGURATION}\")")
    Wni(b, "set_property(CACHE TARGET_CONFIGURATION PROPERTY STRINGS ${ALLOWED_TARGET_CONFIGURATIONS})")
    Wni(b, "project(")
    Wwi(b, 1, "Jafg")
    Wwi(b, 1, "VERSION 0.0.1")
    Wwi(b, 1, "LANGUAGES C CXX")
    Wwi(b, 1, "DESCRIPTION \"S-Jafg\"")
    Wwi(b, 1, ")")
    Wni(b, "set(CMAKE_CXX_STANDARD 20)")
    Wni(b, "set(CMAKE_CXX_STANDARD_REQUIRED ON)")
    Wni(b, "set(CMAKE_CXX_EXTENSIONS ON)")
    Wni(b, fmt.Sprintf("set(REL_ENGINE_ROOT_DIR \"${CMAKE_SOURCE_DIR}/%s\")", sln.GetChdirUpRelToBuildFile()))
    Wni(b, "get_filename_component(REAL_ENGINE_ROOT_DIR ${REL_ENGINE_ROOT_DIR} REALPATH)")
    Wni(b, "if(NOT REAL_ENGINE_ROOT_DIR)")
    Wwi(b, 1, "message(FATAL_ERROR \"REAL_ENGINE_ROOT_DIR is not defined. Something critical went wrong. Rel path: [${REL_ENGINE_ROOT_DIR}].\")")
    Wni(b, "endif()")
    Wni(b, "message(STATUS \"Detected C compiler: ${CMAKE_C_COMPILER}\")")
    Wni(b, "message(STATUS \"Detected CXX compiler: ${CMAKE_CXX_COMPILER}\")")
    Wni(b, "message(STATUS \"Hosting on: ${CMAKE_HOST_SYSTEM_NAME}\")")
    Wni(b, "message(STATUS \"With CXX_COMPILER_ID: ${CMAKE_CXX_COMPILER_ID}\")")
    Wni(b, "message(STATUS \"With CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}\")")
    Wni(b, "message(STATUS \"With CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}\")")
    Wni(b, "message(STATUS \"With REL_ENGINE_ROOT_DIR: ${REL_ENGINE_ROOT_DIR}\")")
    Wni(b, "message(STATUS \"With REAL_ENGINE_ROOT_DIR: ${REAL_ENGINE_ROOT_DIR}\")")
    Wni(b, "if(TARGET_PLATFORM STREQUAL \"Windows64\")")
    Wwi(b, 1, "if(NOT CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\")")
    Wwi(b, 2, "message(FATAL_ERROR \"The CXX compiler must be MSVC for the Windows platform. Detected: [${CMAKE_CXX_COMPILER_ID}].\")")
    Wwi(b, 1, "endif()")
    Wwi(b, 1, "set(CMAKE_SYSTEM_NAME Windows)")
    Wwi(b, 1, "set(CMAKE_GENERATOR_PLATFORM x64)")
    Wwi(b, 1, "set(COMPILER_SUPPORTS_SHARED_LNK ON)")
    Wwi(b, 1, "add_compile_definitions(PLATFORM_WINDOWS)")
    Wwi(b, 1, "add_compile_definitions(PLATFORM_WINDOWS_WITH_MSVC)")
    Wni(b, "elseif(TARGET_PLATFORM STREQUAL \"Windows32FastWasm\")")
    Wwi(b, 1, "if(NOT CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\")")
    Wwi(b, 2, "message(FATAL_ERROR \"The CXX compiler must be GNU for the Windows32FastWasm platform. Detected: [${CMAKE_CXX_COMPILER_ID}].\")")
    Wwi(b, 1, "endif()")
    Wwi(b, 1, "set(CMAKE_SYSTEM_NAME Windows)")
    Wwi(b, 1, "set(CMAKE_GENERATOR_PLATFORM Win32)")
    Wwi(b, 1, "set(COMPILER_SUPPORTS_SHARED_LNK ON)")
    Wwi(b, 1, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -m32\")")
    Wwi(b, 1, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -m32\")")
    Wwi(b, 1, "add_compile_definitions(PLATFORM_WINDOWS)")
    Wwi(b, 1, "add_compile_definitions(PLATFORM_WINDOWS_WITH_GCC)")
    Wni(b, "elseif(TARGET_PLATFORM STREQUAL \"Wasm\")")
    Wwi(b, 1, "string(REGEX MATCH \".*em\\\\+\\\\+.*\" REGREX_MATCHED ${CMAKE_CXX_COMPILER})")
    Wwi(b, 1, "if(NOT REGREX_MATCHED)")
    Wwi(b, 2, "message(FATAL_ERROR \"The CXX compiler must be em++ for the Wasm platform. Detected: [${CMAKE_CXX_COMPILER_ID}].\")")
    Wwi(b, 1, "endif()")
    Wwi(b, 1, "set(COMPILER_SUPPORTS_SHARED_LNK OFF)")
    Wwi(b, 1, "add_compile_definitions(PLATFORM_WASM)")
    Wni(b, "endif()")
    Wni(b, "if(CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\")")
    Wwi(b, 1, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /Zc:__cplusplus\")")
    Wwi(b, 1, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /GR- /Zc:__cplusplus\")")
    for _, t := range sln.Targets {
        Wwi(b, 1, fmt.Sprintf("if(TARGET_CONFIGURATION STREQUAL \"%s\")", t.Name))
        Wwi(b, 2, "add_compile_definitions(")
        for _, d := range t.Defines {
            Wwi(b, 3, fmt.Sprintf("%s", d))
        }
        Wwi(b, 2, ")")
        Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /W3\")")
        Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /W3\")")
        if t.Symbols {
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /Zi\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /Zi\")")
            Wwi(b, 2, "set(CMAKE_SHARED_LINKER_FLAGS \"${CMAKE_SHARED_LINKER_FLAGS} /DEBUG\")")
            Wwi(b, 2, "set(CMAKE_EXE_LINKER_FLAGS \"${CMAKE_EXE_LINKER_FLAGS} /DEBUG\")")
        } else {
            Wwi(b, 2, "set(CMAKE_SHARED_LINKER_FLAGS \"${CMAKE_SHARED_LINKER_FLAGS} /DEBUG:NONE\")")
        }
        if !t.Optimize {
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /Od\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /Od\")")
        } else if t.Optimize && t.Symbols {
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /O2\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /O2\")")
        } else if t.Optimize && !t.Symbols { // /fp:fast?
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} /Ox /GL\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} /Ox /GL\")") // DANGEROUS /GL may not what we want to use. We shall see.
        }
        Wwi(b, 1, "endif()")
        continue
    }
    Wni(b, "else(CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\")")
    Wwi(b, 1, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -fno-rtti\")") // -fno-exceptions?
    for _, t := range sln.Targets {
        Wwi(b, 1, fmt.Sprintf("if(TARGET_CONFIGURATION STREQUAL \"%s\")", t.Name))
        Wwi(b, 2, "add_compile_definitions(")
        for _, d := range t.Defines {
            Wwi(b, 3, fmt.Sprintf("%s", d))
        }
        Wwi(b, 2, ")")
        Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -Wall -Wextra\")")
        Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -Wall -Wextra\")")
        if t.Symbols {
            Wwi(b, 2, "set(CMAKE_X_FLAGS \"${CMAKE_C_FLAGS} -g\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -g\")")
        }
        if !t.Optimize {
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -O0\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -O0\")")
        } else if t.Optimize && t.Symbols {
            Wwi(b, 2, "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -O2\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -O2\")")
        } else if t.Optimize && !t.Symbols {
            Wwi(b, 2, "set(CMAKE_X_FLAGS \"${CMAKE_X_FLAGS} -O3 -flto\")")
            Wwi(b, 2, "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -O3 -flto\")")
        }
        Wwi(b, 1, "endif()")
        continue
    }
    Wni(b, "endif()")
    Wni(b, "message(STATUS \"CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}\")")
    Wni(b, "message(STATUS \"CMAKE_GENERATOR_PLATFORM: ${CMAKE_GENERATOR_PLATFORM}\")")
    Wni(b, "message(STATUS \"CMAKE_C_FLAGS: ${CMAKE_C_FLAGS}\")")
    Wni(b, "message(STATUS \"CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}\")")
    Wni(b, "message(STATUS \"CMAKE_SHARED_LINKER_FLAGS: ${CMAKE_SHARED_LINKER_FLAGS}\")")
    Wni(b, "message(STATUS \"CMAKE_EXE_LINKER_FLAGS: ${CMAKE_EXE_LINKER_FLAGS}\")")
    if GbPredefineJafgMacros {
        Wni(b, "add_compile_definitions(")
        Wwi(b, 1, "DECLARE_JAFG_CLASS")
        Wwi(b, 1, "GENERATED_CLASS_BODY")
        Wwi(b, 1, ")")
    }

    // For generated files only. NOT FOR SOURCE FILES.
    Wni(b, "include_directories(${REAL_ENGINE_ROOT_DIR})")

    // All modules have to exist in the same solution. So we just iterate over the first one.
    for idx, _ := range sln.Targets[0].Modules {
        var module *Core.Module = &sln.Targets[0].Modules[idx]

        Wni(b, "\n############################")
        Wni(b, fmt.Sprintf("# Module: %s", module.Name))
        Wni(b, "############################")
        Wni(b, fmt.Sprintf("message(STATUS \"Adding module [%s] ...\")", module.Name))

        Wni(b, fmt.Sprintf("file(GLOB_RECURSE %s_SRC_FILES", module.Name))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/*.md\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/*.py\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/*.h\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/*.hpp\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/*.c\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/*.cpp\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, ")")
        //Wwi(b, 1, fmt.Sprintf("source_group(TREE ${REAL_ENGINE_ROOT_DIR} FILES ${%s_SRC_FILES})", module.Name))
        Wwi(b, 1, fmt.Sprintf("source_group(\"My Files\" FILES ${%s_SRC_FILES})", module.Name))
        Wni(b, fmt.Sprintf("file(GLOB_RECURSE %s_C_SRC_FILES", module.Name))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/*.c\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, ")")
        Wni(b, fmt.Sprintf("file(GLOB_RECURSE %s_GEN_SRC_FILES", module.Name))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/*%s\"", sln.GetSavedRelativeDir(), module.GetFunctionalRelativeDir(), Core.GhDir, Core.GhExtension))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/*%s\"", sln.GetSavedRelativeDir(), module.GetFunctionalRelativeDir(), Core.GtDir, Core.GtExtension))
        Wwi(b, 1, ")")

        for i, _ := range sln.Targets {
            volatileTarget := &sln.Targets[i]
            volatileModule := &volatileTarget.Modules[idx]
            Wni(b, fmt.Sprintf("if(TARGET_CONFIGURATION STREQUAL \"%s\")", volatileTarget.Name))

            Wwi(b, 1, fmt.Sprintf("file(GLOB_RECURSE %s_COND_GEN_SRC_FILES", module.Name))
            Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/%s/*%s\"", sln.GetSavedRelativeDir(), volatileModule.GetFunctionalRelativeDir(), Core.CghDir, volatileTarget.Name, Core.GhExtension))
            Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/%s/*%s\"", sln.GetSavedRelativeDir(), volatileModule.GetFunctionalRelativeDir(), Core.CgtDir, volatileTarget.Name, Core.GtExtension))
            Wwi(b, 2, ")")

            Wni(b, "endif()")
            continue
        }
        Wni(b, fmt.Sprintf("if(NOT DEFINED %s_COND_GEN_SRC_FILES)", module.Name))
        Wwi(b, 1, fmt.Sprintf("message(FATAL_ERROR \"No conditional generated source files found for module [%s].\")", module.Name))
        Wni(b, "endif()")

        if module.Kind.IsLaunch() {
            Wni(b, fmt.Sprintf("add_executable(%s ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_COND_GEN_SRC_FILES})", module.Name, module.Name, module.Name, module.Name))
        } else {
            Wni(b, "if(COMPILER_SUPPORTS_SHARED_LNK)")
            Wwi(b, 1, fmt.Sprintf("add_library(%s %s ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_COND_GEN_SRC_FILES})", module.Name, module.Kind.ToCMakeString(), module.Name, module.Name, module.Name))
            Wni(b, "else()")
            Wwi(b, 1, fmt.Sprintf("add_library(%s STATIC ${%s_SRC_FILES} ${%s_GEN_SRC_FILES} ${%s_COND_GEN_SRC_FILES})", module.Name, module.Name, module.Name, module.Name))
            Wni(b, "endif()")
        }

        Wni(b, fmt.Sprintf("foreach(src_file ${%s_C_SRC_FILES})", module.Name))
        Wwi(b, 1, "set_source_files_properties(${src_file} PROPERTIES LANGUAGE C)")
        Wwi(b, 1, "set_source_files_properties(${src_file} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)")
        Wni(b, "endforeach()")

        Wni(b, fmt.Sprintf("target_include_directories(%s PUBLIC", module.Name))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/Public\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s\"", sln.GetSavedRelativeDir(), module.GetFunctionalRelativeDir(), Core.GhDir))
        Wwi(b, 1, ")")
        Wni(b, fmt.Sprintf("target_include_directories(%s PRIVATE", module.Name))
        Wwi(b, 1, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/Internal\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, ")")

        Wni(b, fmt.Sprintf("set_target_properties(%s PROPERTIES", module.Name))
        Wwi(b, 1, fmt.Sprintf("ARCHIVE_OUTPUT_DIRECTORY \"${REAL_ENGINE_ROOT_DIR}/Binaries/${TARGET_PLATFORM}-${CMAKE_SYSTEM_PROCESSOR}/${TARGET_CONFIGURATION}/%s\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("LIBRARY_OUTPUT_DIRECTORY \"${REAL_ENGINE_ROOT_DIR}/Binaries/${TARGET_PLATFORM}-${CMAKE_SYSTEM_PROCESSOR}/${TARGET_CONFIGURATION}/%s\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, fmt.Sprintf("RUNTIME_OUTPUT_DIRECTORY \"${REAL_ENGINE_ROOT_DIR}/Binaries/${TARGET_PLATFORM}-${CMAKE_SYSTEM_PROCESSOR}/${TARGET_CONFIGURATION}/%s\"", module.GetFunctionalRelativeDir()))
        Wwi(b, 1, ")")

        Wni(b, "if(TARGET_PLATFORM STREQUAL TARGET_PLATFORM_WASM)")
        Wwi(b, 1, fmt.Sprintf("set_target_properties(%s PROPERTIES", module.Name))
        Wwi(b, 2, "LINK_FLAGS \"-sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sUSE_FREETYPE=1 -sUSE_PTHREADS=1 -sPTHREAD_POOL_SIZE_STRICT=2 -sPTHREAD_POOL_SIZE=3 -sALLOW_MEMORY_GROWTH --shell-file ${REAL_ENGINE_ROOT_DIR}/Content/Wasm/MinimalShell.html\"")
        Wwi(b, 2, "SUFFIX \".html\"")
        Wwi(b, 2, "COMPILE_FLAGS \"-pthread\"")
        Wwi(b, 2, ")")
        Wni(b, "endif()")

        for i, _ := range sln.Targets {
            volatileTarget := &sln.Targets[i]
            volatileModule := &volatileTarget.Modules[idx]
            var transitiveDependencies []*Core.Module
            volatileModule.GetTransitiveAllDependencies(volatileTarget, &transitiveDependencies)
            Wni(b, fmt.Sprintf("if(TARGET_CONFIGURATION STREQUAL \"%s\")", volatileTarget.Name))

            if volatileModule.PchUsage.IsAllowed() {
                Wwi(b, 1, fmt.Sprintf("target_precompile_headers(%s PRIVATE \"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/%s/%s\")",
                    volatileModule.Name, sln.GetSavedRelativeDir(), volatileModule.GetFunctionalRelativeDir(), Core.CghDir, volatileTarget.Name, Core.FilePath_PchHeader))
            }

            if volatileModule.Kind.IsLaunch() {
                Wwi(b, 1, "if(TARGET_PLATFORM STREQUAL \"Windows64\")")
                Wwi(b, 2, "if(CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\")")
                Wwi(b, 3, fmt.Sprintf("set_target_properties(%s PROPERTIES LINK_FLAGS \"/SUBSYSTEM:WINDOWS\")", volatileModule.Name))
                Wwi(b, 2, "elseif(CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\")")
                Wwi(b, 3, fmt.Sprintf("set_target_properties(%s PROPERTIES LINK_FLAGS \"-mwindows\")", volatileModule.Name))
                Wwi(b, 2, "endif()")
                Wwi(b, 1, "endif()")
            }

            Wwi(b, 1, fmt.Sprintf("target_include_directories(%s PRIVATE", volatileModule.Name))
            Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s/%s\"", sln.GetSavedRelativeDir(), volatileModule.GetFunctionalRelativeDir(), Core.CghDir, volatileTarget.Name))
            for _, d := range transitiveDependencies {
                if !d.IsEqual(volatileModule) {
                    Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/Source/Public\"", d.GetFunctionalRelativeDir()))
                    Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s/%s/%s\"", sln.GetSavedRelativeDir(), d.GetFunctionalRelativeDir(), Core.GhDir))
                }
            }
            for _, d := range volatileModule.NativeIncludeDirs {
                Wwi(b, 2, fmt.Sprintf("\"${REAL_ENGINE_ROOT_DIR}/%s\"", d))
            }
            Wwi(b, 2, ")")

            Wwi(b, 1, fmt.Sprintf("target_link_libraries(%s PRIVATE", volatileModule.Name))
            for _, d := range transitiveDependencies {
                if !d.IsEqual(volatileModule) {
                    Wwi(b, 2, fmt.Sprintf("%s", d.Name))
                }
            }
            Wwi(b, 2, ")")
            Wwi(b, 1, "if(NOT TARGET_PLATFORM STREQUAL TARGET_PLATFORM_WASM)")
            Wwi(b, 2, fmt.Sprintf("target_link_libraries(%s PRIVATE", volatileModule.Name))
            for _, d := range volatileModule.NativeDependencies {
                if !strings.HasSuffix(d, ".dll") { // Do not link the .dll but only the associated .lib - this of course has to exist.
                    Wwi(b, 3, fmt.Sprintf("${REAL_ENGINE_ROOT_DIR}/%s", d))
                }
            }
            Wwi(b, 3, ")")
            Wwi(b, 1, "endif()")

            Wwi(b, 1, fmt.Sprintf("if(TARGET_PLATFORM STREQUAL TARGET_PLATFORM_WASM)"))
            Wwi(b, 2, fmt.Sprintf("target_compile_definitions(%s PRIVATE", volatileModule.Name))
            for _, mod := range volatileTarget.Modules {
                if !Shared.ContainsByPredicate(transitiveDependencies, func(m *Core.Module) bool { return mod.IsEqual(m) }) {
                    continue
                }
                Wwi(b, 3, fmt.Sprintf("%s_API=", strings.ToUpper(mod.Name)))
                Wwi(b, 3, fmt.Sprintf("%s_EXTERN=", strings.ToUpper(mod.Name)))
                continue
            }
            Wwi(b, 3, ")")
            Wwi(b, 1, "else()")
            Wwi(b, 2, fmt.Sprintf("target_compile_definitions(%s PRIVATE", volatileModule.Name))
            for _, mod := range volatileTarget.Modules {
                if !Shared.ContainsByPredicate(transitiveDependencies, func(m *Core.Module) bool { return mod.IsEqual(m) }) {
                    continue
                }

                if mod.IsEqual(volatileModule) {
                    if volatileModule.Kind.IsShared() {
                        Wwi(b, 3, fmt.Sprintf("%s_API=PLATFORM_CALLSPEC_OUT", strings.ToUpper(mod.Name)))
                        Wwi(b, 3, fmt.Sprintf("%s_EXTERN=PLATFORM_EXTERNSPEC_OUT", strings.ToUpper(mod.Name)))
                    } else {
                        Wwi(b, 3, fmt.Sprintf("%s_API=", strings.ToUpper(mod.Name)))
                        Wwi(b, 3, fmt.Sprintf("%s_EXTERN=", strings.ToUpper(mod.Name)))
                    }
                } else if mod.Kind.IsLaunch() {
                    panic(fmt.Sprintf("Launch dependencies are not allowed. Faulty dependency: %s.", mod.Name))
                } else if mod.Kind.IsShared() {
                    Wwi(b, 3, fmt.Sprintf("%s_API=PLATFORM_CALLSPEC_IN", strings.ToUpper(mod.Name)))
                    Wwi(b, 3, fmt.Sprintf("%s_EXTERN=PLATFORM_EXTERNSPEC_IN", strings.ToUpper(mod.Name)))
                } else if mod.Kind.IsStatic() {
                    Wwi(b, 3, fmt.Sprintf("%s_API=", strings.ToUpper(mod.Name)))
                    Wwi(b, 3, fmt.Sprintf("%s_EXTERN=", strings.ToUpper(mod.Name)))
                } else {
                    panic(fmt.Sprintf("Unknown module kind: %s.", mod.Kind.ToLuaString()))
                }

                continue
            }
            Wwi(b, 3, ")")
            Wwi(b, 1, "endif()")

            Wwi(b, 1, fmt.Sprintf("get_target_property(TARGET_KIND %s TYPE)", volatileModule.Name))
            Wwi(b, 1, "if(CMAKE_HOST_SYSTEM_NAME STREQUAL \"Windows\")")
            Wwi(b, 2, fmt.Sprintf("add_custom_target(%s_PRE_BUILD_COMMAND", volatileModule.Name))
            Wwi(b, 3,fmt.Sprintf("COMMENT \"Launching Pre-build events module [%s] ...\"", volatileModule.Name))
            Wwi(b, 3, fmt.Sprintf("COMMAND \"${REAL_ENGINE_ROOT_DIR}/%s/Scripts/python.exe\" \"${REAL_ENGINE_ROOT_DIR}/Program.py\" ", Core.DirPath_Venv)+
                "--INVOKE --BuildTool pre-build "+
                fmt.Sprintf("SLN=%s ", sln.Name)+
                fmt.Sprintf("MODULE=%s ", volatileModule.GetUniqueName())+
                "KIND=${TARGET_KIND} "+
                "PLATFORM=${TARGET_PLATFORM} ARCH=${CMAKE_SYSTEM_PROCESSOR} "+
                "TARGET=${TARGET_CONFIGURATION}",
            )
            Wwi(b, 3, ")")
            Wwi(b, 2, fmt.Sprintf("add_dependencies(%s %s_PRE_BUILD_COMMAND)", volatileModule.Name, volatileModule.Name))
            Wwi(b, 2, fmt.Sprintf("add_custom_command(TARGET %s POST_BUILD", volatileModule.Name))
            Wwi(b, 3,fmt.Sprintf("COMMENT \"Launching Post-build events module [%s] ...\"", volatileModule.Name))
            Wwi(b, 3, fmt.Sprintf("COMMAND \"${REAL_ENGINE_ROOT_DIR}/%s/Scripts/python.exe\" \"${REAL_ENGINE_ROOT_DIR}/Program.py\" ", Core.DirPath_Venv)+
                "--INVOKE --BuildTool post-build "+
                fmt.Sprintf("SLN=%s ", sln.Name)+
                fmt.Sprintf("MODULE=%s ", volatileModule.GetUniqueName())+
                "KIND=${TARGET_KIND} "+
                "PLATFORM=${TARGET_PLATFORM} ARCH=${CMAKE_SYSTEM_PROCESSOR} "+
                "TARGET=${TARGET_CONFIGURATION}",
            )
            Wwi(b, 3, ")")
            Wwi(b, 1 , "else()")
            Wwi(b, 2, "message(FATAL_ERROR \"Unsupported host system: ${CMAKE_HOST_SYSTEM_NAME}.\")")
            Wwi(b, 1 , "endif()")

            Wni(b, "endif()")
            continue
        }

        continue
    }

    Shared.OpenAndWriteToRelativeFileIfDifferent(fPath, b.String(), true)
    fmt.Println("Finished generating CMake script.")
    return nil
}
