#!/bin/bash

# Copyright mzoesch. All rights reserved.
# This file is automatically generated by Jafg and can be deleted with no fear.
# This file builds then binaries for [Jafg-$SOLUTION_NAME] on the platform [$PLATFORM_NAME] with the build configuration [$NATIVE_BUILD_TARGET].
# You will have to run [generate.X] once before running this file.

set -e

CURRENT_DIR=$(pwd)

$PRE_EXECUTION_COMMAND

cd "$(dirname "$0")"

cmake --build . --clean-first

# read -n1 -r -p "Press any key to continue..."
