#!/bin/bash

# Copyright mzoesch. All rights reserved.
# This file is automatically generated by Jafg and can be deleted with no fear.
# This file builds then binaries for [Jafg-$SOLUTION_NAME] on the platform [$PLATFORM_NAME] with the build configuration [$NATIVE_BUILD_TARGET].

set -e

CURRENT_DIR=$(pwd)

$PRE_EXECUTION_COMMAND

cd "$(dirname "$0")"

cmake --build . 

read -n1 -r -p "Press any key to continue..."
