#!/bin/bash

# Copyright mzoesch. All rights reserved.
# This file is automatically generated by Jafg and can be deleted with no fear.
# This file generates the CMake files for [Jafg-$SOLUTION_NAME] on the platform [$PLATFORM_NAME] with the build configuration [$NATIVE_BUILD_TARGET].

set -e

CURRENT_DIR=$(pwd)

$PRE_EXECUTION_COMMAND

cd "$(dirname "$0")"

cd ..
cd ..

cmake -S . -B "$PLATFORM_NAME-$ARCHITECTURE_NAME/$NATIVE_BUILD_TARGET" -G Ninja -DJAFG_TARGET_PLATFORM=$PLATFORM_NAME -DJAFG_TARGET_CONFIGURATION=$NATIVE_BUILD_TARGET -DJAFG_TARGET_ARCHITECTURE=$ARCHITECTURE_NAME

cd -
cd -

cd "$(dirname "$0")"

# read -n1 -r -p "Press any key to continue..."
