@REM Copyright mzoesch. All rights reserved.
@REM This file is automatically generated by Jafg and can be deleted with no fear.
@REM This file builds then binaries for [Jafg-$SOLUTION_NAME] on the platform [$PLATFORM_NAME] with the build configuration [$NATIVE_BUILD_TARGET].
@REM You will have to run [generate.X] once before running this file.

@echo off

set CURRENT_DIR=%cd%

$PRE_EXECUTION_COMMAND

cd /d %~dp0

pushd ..
pushd ..

emcmake cmake -S . -B "$PLATFORM_NAME-$ARCHITECTURE_NAME/$NATIVE_BUILD_TARGET" -G Ninja -DJAFG_TARGET_PLATFORM=$PLATFORM_NAME -DJAFG_TARGET_CONFIGURATION=$NATIVE_BUILD_TARGET -DJAFG_TARGET_ARCHITECTURE=$ARCHITECTURE_NAME

popd
popd

cd /d %CURRENT_DIR%

pause
