@REM Copyright mzoesch. All rights reserved.
@REM This file is automatically generated by Jafg and can be deleted with no fear.
@REM This file builds then binaries for [Jafg-$SOLUTION_NAME] on the platform [$PLATFORM_NAME] with the build configuration [$NATIVE_BUILD_TARGET].

@echo off

set CURRENT_DIR=%cd%

$PRE_EXECUTION_COMMAND

cd /d %~dp0

cmake --build . 

pause
