// Copyright mzoesch. All rights reserved.

#include "Maths/Color.h"

LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkerGray                 { Jafg::LLinearColor::FromColor( 0x1A, 0x1A, 0x1A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkerGrey                 { Jafg::LLinearColor::FromColor( 0x1A, 0x1A, 0x1A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::NotSoDarkGray              { Jafg::LLinearColor::FromColor( 0x2B, 0x2B, 0x2B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::NotSoDarkGrey              { Jafg::LLinearColor::FromColor( 0x2B, 0x2B, 0x2B, 0xFF ) };

LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Aliceblue                  { Jafg::LLinearColor::FromColor( 0xF0, 0xF8, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Antiquewhite               { Jafg::LLinearColor::FromColor( 0xFA, 0xEB, 0xD7, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Aqua                       { Jafg::LLinearColor::FromColor( 0x00, 0xFF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Aquamarine                 { Jafg::LLinearColor::FromColor( 0x7F, 0xFF, 0xD4, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Azure                      { Jafg::LLinearColor::FromColor( 0xF0, 0xFF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Beige                      { Jafg::LLinearColor::FromColor( 0xF5, 0xF5, 0xDC, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Bisque                     { Jafg::LLinearColor::FromColor( 0xFF, 0xE4, 0xC4, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Black                      { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Blanchedalmond             { Jafg::LLinearColor::FromColor( 0xFF, 0xEB, 0xCD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Blue                       { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::BlueViolet                 { Jafg::LLinearColor::FromColor( 0x8A, 0x2B, 0xE2, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Brown                      { Jafg::LLinearColor::FromColor( 0xA5, 0x2A, 0x2A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::BurlyWood                  { Jafg::LLinearColor::FromColor( 0xDE, 0xB8, 0x87, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::CadetBlue                  { Jafg::LLinearColor::FromColor( 0x5F, 0x9E, 0xA0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Chartreuse                 { Jafg::LLinearColor::FromColor( 0x7F, 0xFF, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Chocolate                  { Jafg::LLinearColor::FromColor( 0xD2, 0x69, 0x1E, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Coral                      { Jafg::LLinearColor::FromColor( 0xFF, 0x7F, 0x50, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::CornflowerBlue             { Jafg::LLinearColor::FromColor( 0x64, 0x95, 0xED, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Cornsilk                   { Jafg::LLinearColor::FromColor( 0xFF, 0xF8, 0xDC, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Crimson                    { Jafg::LLinearColor::FromColor( 0xDC, 0x14, 0x3C, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Cyan                       { Jafg::LLinearColor::FromColor( 0x00, 0xFF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkBlue                   { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0x8B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkCyan                   { Jafg::LLinearColor::FromColor( 0x00, 0x8B, 0x8B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkGoldenRod              { Jafg::LLinearColor::FromColor( 0xB8, 0x86, 0x0B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkGray                   { Jafg::LLinearColor::FromColor( 0xA9, 0xA9, 0xA9, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkGreen                  { Jafg::LLinearColor::FromColor( 0x00, 0x64, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkGrey                   { Jafg::LLinearColor::FromColor( 0xA9, 0xA9, 0xA9, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkKhaki                  { Jafg::LLinearColor::FromColor( 0xBD, 0xB7, 0x6B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkMagenta                { Jafg::LLinearColor::FromColor( 0x8B, 0x00, 0x8B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkOliveGreen             { Jafg::LLinearColor::FromColor( 0x55, 0x6B, 0x2F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkOrange                 { Jafg::LLinearColor::FromColor( 0xFF, 0x8C, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkOrchid                 { Jafg::LLinearColor::FromColor( 0x99, 0x32, 0xCC, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkRed                    { Jafg::LLinearColor::FromColor( 0x8B, 0x00, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkSalmon                 { Jafg::LLinearColor::FromColor( 0xE9, 0x96, 0x7A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkSeaGreen               { Jafg::LLinearColor::FromColor( 0x8F, 0xBC, 0x8F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkSlateBlue              { Jafg::LLinearColor::FromColor( 0x48, 0x3D, 0x8B, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkSlateGray              { Jafg::LLinearColor::FromColor( 0x2F, 0x4F, 0x4F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkSlateGrey              { Jafg::LLinearColor::FromColor( 0x2F, 0x4F, 0x4F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkTurquoise              { Jafg::LLinearColor::FromColor( 0x00, 0xCE, 0xD1, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DarkViolet                 { Jafg::LLinearColor::FromColor( 0x94, 0x00, 0xD3, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DeepPink                   { Jafg::LLinearColor::FromColor( 0xFF, 0x14, 0x93, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DeepSkyBlue                { Jafg::LLinearColor::FromColor( 0x00, 0xBF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DimGray                    { Jafg::LLinearColor::FromColor( 0x69, 0x69, 0x69, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DimGrey                    { Jafg::LLinearColor::FromColor( 0x69, 0x69, 0x69, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::DodgerBlue                 { Jafg::LLinearColor::FromColor( 0x1E, 0x90, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::FireBrick                  { Jafg::LLinearColor::FromColor( 0xB2, 0x22, 0x22, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::FloralWhite                { Jafg::LLinearColor::FromColor( 0xFF, 0xFA, 0xF0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::ForestGreen                { Jafg::LLinearColor::FromColor( 0x22, 0x8B, 0x22, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Fuchsia                    { Jafg::LLinearColor::FromColor( 0xFF, 0x00, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Gainsboro                  { Jafg::LLinearColor::FromColor( 0xDC, 0xDC, 0xDC, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::GhostWhite                 { Jafg::LLinearColor::FromColor( 0xF8, 0xF8, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Gold                       { Jafg::LLinearColor::FromColor( 0xFF, 0xD7, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Goldenrod                  { Jafg::LLinearColor::FromColor( 0xDA, 0xA5, 0x20, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Gray                       { Jafg::LLinearColor::FromColor( 0x80, 0x80, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Green                      { Jafg::LLinearColor::FromColor( 0x00, 0x80, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::GreenYellow                { Jafg::LLinearColor::FromColor( 0xAD, 0xFF, 0x2F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Grey                       { Jafg::LLinearColor::FromColor( 0x80, 0x80, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Honeydew                   { Jafg::LLinearColor::FromColor( 0xF0, 0xFF, 0xF0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::HotPink                    { Jafg::LLinearColor::FromColor( 0xFF, 0x69, 0xB4, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Indianred                  { Jafg::LLinearColor::FromColor( 0xCD, 0x5C, 0x5C, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Indigo                     { Jafg::LLinearColor::FromColor( 0x4B, 0x00, 0x82, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Ivory                      { Jafg::LLinearColor::FromColor( 0xFF, 0xFF, 0xF0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Khaki                      { Jafg::LLinearColor::FromColor( 0xF0, 0xE6, 0x8C, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Lavender                   { Jafg::LLinearColor::FromColor( 0xE6, 0xE6, 0xFA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LavenderBlush              { Jafg::LLinearColor::FromColor( 0xFF, 0xF0, 0xF5, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LawnGreen                  { Jafg::LLinearColor::FromColor( 0x7C, 0xFC, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LemonChiffon               { Jafg::LLinearColor::FromColor( 0xFF, 0xFA, 0xCD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightBlue                  { Jafg::LLinearColor::FromColor( 0xAD, 0xD8, 0xE6, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightCoral                 { Jafg::LLinearColor::FromColor( 0xF0, 0x80, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightCyan                  { Jafg::LLinearColor::FromColor( 0xE0, 0xFF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightGoldenrodYellow       { Jafg::LLinearColor::FromColor( 0xFA, 0xFA, 0xD2, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightGray                  { Jafg::LLinearColor::FromColor( 0xD3, 0xD3, 0xD3, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightGreen                 { Jafg::LLinearColor::FromColor( 0x90, 0xEE, 0x90, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightGrey                  { Jafg::LLinearColor::FromColor( 0xD3, 0xD3, 0xD3, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightPink                  { Jafg::LLinearColor::FromColor( 0xFF, 0xB6, 0xC1, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSalmon                { Jafg::LLinearColor::FromColor( 0xFF, 0xA0, 0x7A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSeagreen              { Jafg::LLinearColor::FromColor( 0x20, 0xB2, 0xAA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSkyBlue               { Jafg::LLinearColor::FromColor( 0x87, 0xCE, 0xFA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSlateGray             { Jafg::LLinearColor::FromColor( 0x77, 0x88, 0x99, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSlateGrey             { Jafg::LLinearColor::FromColor( 0x77, 0x88, 0x99, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightSteelBlue             { Jafg::LLinearColor::FromColor( 0xB0, 0xC4, 0xDE, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LightYellow                { Jafg::LLinearColor::FromColor( 0xFF, 0xFF, 0xE0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Lime                       { Jafg::LLinearColor::FromColor( 0x00, 0xFF, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::LimeGreen                  { Jafg::LLinearColor::FromColor( 0x32, 0xCD, 0x32, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Linen                      { Jafg::LLinearColor::FromColor( 0xFA, 0xF0, 0xE6, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Magenta                    { Jafg::LLinearColor::FromColor( 0xFF, 0x00, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Maroon                     { Jafg::LLinearColor::FromColor( 0x80, 0x00, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumAquaMarine           { Jafg::LLinearColor::FromColor( 0x66, 0xCD, 0xAA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumBlue                 { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0xCD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumOrchid               { Jafg::LLinearColor::FromColor( 0xBA, 0x55, 0xD3, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumPurple               { Jafg::LLinearColor::FromColor( 0x93, 0x70, 0xDB, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumSeagreen             { Jafg::LLinearColor::FromColor( 0x3C, 0xB3, 0x71, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumSlateBlue            { Jafg::LLinearColor::FromColor( 0x7B, 0x68, 0xEE, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumSpringGreen          { Jafg::LLinearColor::FromColor( 0x00, 0xFA, 0x9A, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumTurquoise            { Jafg::LLinearColor::FromColor( 0x48, 0xD1, 0xCC, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MediumVioletRed            { Jafg::LLinearColor::FromColor( 0xC7, 0x15, 0x85, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MidnightBlue               { Jafg::LLinearColor::FromColor( 0x19, 0x19, 0x70, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::MintCream                  { Jafg::LLinearColor::FromColor( 0xF5, 0xFF, 0xFA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Mistyrose                  { Jafg::LLinearColor::FromColor( 0xFF, 0xE4, 0xE1, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Moccasin                   { Jafg::LLinearColor::FromColor( 0xFF, 0xE4, 0xB5, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::NavajoWhite                { Jafg::LLinearColor::FromColor( 0xFF, 0xDE, 0xAD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Navy                       { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Oldlace                    { Jafg::LLinearColor::FromColor( 0xFD, 0xF5, 0xE6, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Olive                      { Jafg::LLinearColor::FromColor( 0x80, 0x80, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Olivedrab                  { Jafg::LLinearColor::FromColor( 0x6B, 0x8E, 0x23, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Orange                     { Jafg::LLinearColor::FromColor( 0xFF, 0xA5, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Orangered                  { Jafg::LLinearColor::FromColor( 0xFF, 0x45, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Orchid                     { Jafg::LLinearColor::FromColor( 0xDA, 0x70, 0xD6, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::PaleGoldenRod              { Jafg::LLinearColor::FromColor( 0xEE, 0xE8, 0xAA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::PaleGreen                  { Jafg::LLinearColor::FromColor( 0x98, 0xFB, 0x98, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::PaleTurquoise              { Jafg::LLinearColor::FromColor( 0xAF, 0xEE, 0xEE, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::PaleVioletRed              { Jafg::LLinearColor::FromColor( 0xDB, 0x70, 0x93, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Papayawhip                 { Jafg::LLinearColor::FromColor( 0xFF, 0xEF, 0xD5, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Peachpuff                  { Jafg::LLinearColor::FromColor( 0xFF, 0xDA, 0xB9, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Peru                       { Jafg::LLinearColor::FromColor( 0xCD, 0x85, 0x3F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Pink                       { Jafg::LLinearColor::FromColor( 0xFF, 0xC0, 0xCB, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Plum                       { Jafg::LLinearColor::FromColor( 0xDD, 0xA0, 0xDD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::PowderBlue                 { Jafg::LLinearColor::FromColor( 0xB0, 0xE0, 0xE6, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Purple                     { Jafg::LLinearColor::FromColor( 0x80, 0x00, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::RebeccaPurple              { Jafg::LLinearColor::FromColor( 0x66, 0x33, 0x99, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Red                        { Jafg::LLinearColor::FromColor( 0xFF, 0x00, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::RosyBrown                  { Jafg::LLinearColor::FromColor( 0xBC, 0x8F, 0x8F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::RoyalBlue                  { Jafg::LLinearColor::FromColor( 0x41, 0x69, 0xE1, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SaddleBrown                { Jafg::LLinearColor::FromColor( 0x8B, 0x45, 0x13, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Salmon                     { Jafg::LLinearColor::FromColor( 0xFA, 0x80, 0x72, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SandyBrown                 { Jafg::LLinearColor::FromColor( 0xF4, 0xA4, 0x60, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SeaGreen                   { Jafg::LLinearColor::FromColor( 0x2E, 0x8B, 0x57, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Seashell                   { Jafg::LLinearColor::FromColor( 0xFF, 0xF5, 0xEE, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Sienna                     { Jafg::LLinearColor::FromColor( 0xA0, 0x52, 0x2D, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Silver                     { Jafg::LLinearColor::FromColor( 0xC0, 0xC0, 0xC0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SkyBlue                    { Jafg::LLinearColor::FromColor( 0x87, 0xCE, 0xEB, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SlateBlue                  { Jafg::LLinearColor::FromColor( 0x6A, 0x5A, 0xCD, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SlateGray                  { Jafg::LLinearColor::FromColor( 0x70, 0x80, 0x90, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SlateGrey                  { Jafg::LLinearColor::FromColor( 0x70, 0x80, 0x90, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Snow                       { Jafg::LLinearColor::FromColor( 0xFF, 0xFA, 0xFA, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SpringGreen                { Jafg::LLinearColor::FromColor( 0x00, 0xFF, 0x7F, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::SteelBlue                  { Jafg::LLinearColor::FromColor( 0x46, 0x82, 0xB4, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Tan                        { Jafg::LLinearColor::FromColor( 0xD2, 0xB4, 0x8C, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Teal                       { Jafg::LLinearColor::FromColor( 0x00, 0x80, 0x80, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Thistle                    { Jafg::LLinearColor::FromColor( 0xD8, 0xBF, 0xD8, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Tomato                     { Jafg::LLinearColor::FromColor( 0xFF, 0x63, 0x47, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Transparent                { Jafg::LLinearColor::FromColor( 0x00, 0x00, 0x00, 0x00 ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Turquoise                  { Jafg::LLinearColor::FromColor( 0x40, 0xE0, 0xD0, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Violet                     { Jafg::LLinearColor::FromColor( 0xEE, 0x82, 0xEE, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Wheat                      { Jafg::LLinearColor::FromColor( 0xF5, 0xDE, 0xB3, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::White                      { Jafg::LLinearColor::FromColor( 0xFF, 0xFF, 0xFF, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::WhiteSmoke                 { Jafg::LLinearColor::FromColor( 0xF5, 0xF5, 0xF5, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::Yellow                     { Jafg::LLinearColor::FromColor( 0xFF, 0xFF, 0x00, 0xFF ) };
LAL_API const Jafg::LLinearColor Jafg::LLinearColor::YellowGreen                { Jafg::LLinearColor::FromColor( 0x9A, 0xCD, 0x32, 0xFF ) };

LAL_API const Jafg::LColor Jafg::LColor::DarkerGray                 { 0x1A, 0x1A, 0x1A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkerGrey                 { 0x1A, 0x1A, 0x1A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::NotSoDarkGray              { 0x2B, 0x2B, 0x2B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::NotSoDarkGrey              { 0x2B, 0x2B, 0x2B, 0xFF };

LAL_API const Jafg::LColor Jafg::LColor::Aliceblue                  { 0xF0, 0xF8, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Antiquewhite               { 0xFA, 0xEB, 0xD7, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Aqua                       { 0x00, 0xFF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Aquamarine                 { 0x7F, 0xFF, 0xD4, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Azure                      { 0xF0, 0xFF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Beige                      { 0xF5, 0xF5, 0xDC, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Bisque                     { 0xFF, 0xE4, 0xC4, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Black                      { 0x00, 0x00, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Blanchedalmond             { 0xFF, 0xEB, 0xCD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Blue                       { 0x00, 0x00, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::BlueViolet                 { 0x8A, 0x2B, 0xE2, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Brown                      { 0xA5, 0x2A, 0x2A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::BurlyWood                  { 0xDE, 0xB8, 0x87, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::CadetBlue                  { 0x5F, 0x9E, 0xA0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Chartreuse                 { 0x7F, 0xFF, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Chocolate                  { 0xD2, 0x69, 0x1E, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Coral                      { 0xFF, 0x7F, 0x50, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::CornflowerBlue             { 0x64, 0x95, 0xED, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Cornsilk                   { 0xFF, 0xF8, 0xDC, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Crimson                    { 0xDC, 0x14, 0x3C, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Cyan                       { 0x00, 0xFF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkBlue                   { 0x00, 0x00, 0x8B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkCyan                   { 0x00, 0x8B, 0x8B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkGoldenRod              { 0xB8, 0x86, 0x0B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkGray                   { 0xA9, 0xA9, 0xA9, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkGreen                  { 0x00, 0x64, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkGrey                   { 0xA9, 0xA9, 0xA9, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkKhaki                  { 0xBD, 0xB7, 0x6B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkMagenta                { 0x8B, 0x00, 0x8B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkOliveGreen             { 0x55, 0x6B, 0x2F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkOrange                 { 0xFF, 0x8C, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkOrchid                 { 0x99, 0x32, 0xCC, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkRed                    { 0x8B, 0x00, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkSalmon                 { 0xE9, 0x96, 0x7A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkSeaGreen               { 0x8F, 0xBC, 0x8F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkSlateBlue              { 0x48, 0x3D, 0x8B, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkSlateGray              { 0x2F, 0x4F, 0x4F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkSlateGrey              { 0x2F, 0x4F, 0x4F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkTurquoise              { 0x00, 0xCE, 0xD1, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DarkViolet                 { 0x94, 0x00, 0xD3, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DeepPink                   { 0xFF, 0x14, 0x93, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DeepSkyBlue                { 0x00, 0xBF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DimGray                    { 0x69, 0x69, 0x69, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DimGrey                    { 0x69, 0x69, 0x69, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::DodgerBlue                 { 0x1E, 0x90, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::FireBrick                  { 0xB2, 0x22, 0x22, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::FloralWhite                { 0xFF, 0xFA, 0xF0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::ForestGreen                { 0x22, 0x8B, 0x22, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Fuchsia                    { 0xFF, 0x00, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Gainsboro                  { 0xDC, 0xDC, 0xDC, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::GhostWhite                 { 0xF8, 0xF8, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Gold                       { 0xFF, 0xD7, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Goldenrod                  { 0xDA, 0xA5, 0x20, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Gray                       { 0x80, 0x80, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Green                      { 0x00, 0x80, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::GreenYellow                { 0xAD, 0xFF, 0x2F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Grey                       { 0x80, 0x80, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Honeydew                   { 0xF0, 0xFF, 0xF0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::HotPink                    { 0xFF, 0x69, 0xB4, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Indianred                  { 0xCD, 0x5C, 0x5C, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Indigo                     { 0x4B, 0x00, 0x82, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Ivory                      { 0xFF, 0xFF, 0xF0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Khaki                      { 0xF0, 0xE6, 0x8C, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Lavender                   { 0xE6, 0xE6, 0xFA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LavenderBlush              { 0xFF, 0xF0, 0xF5, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LawnGreen                  { 0x7C, 0xFC, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LemonChiffon               { 0xFF, 0xFA, 0xCD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightBlue                  { 0xAD, 0xD8, 0xE6, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightCoral                 { 0xF0, 0x80, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightCyan                  { 0xE0, 0xFF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightGoldenrodYellow       { 0xFA, 0xFA, 0xD2, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightGray                  { 0xD3, 0xD3, 0xD3, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightGreen                 { 0x90, 0xEE, 0x90, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightGrey                  { 0xD3, 0xD3, 0xD3, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightPink                  { 0xFF, 0xB6, 0xC1, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSalmon                { 0xFF, 0xA0, 0x7A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSeagreen              { 0x20, 0xB2, 0xAA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSkyBlue               { 0x87, 0xCE, 0xFA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSlateGray             { 0x77, 0x88, 0x99, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSlateGrey             { 0x77, 0x88, 0x99, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightSteelBlue             { 0xB0, 0xC4, 0xDE, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LightYellow                { 0xFF, 0xFF, 0xE0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Lime                       { 0x00, 0xFF, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::LimeGreen                  { 0x32, 0xCD, 0x32, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Linen                      { 0xFA, 0xF0, 0xE6, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Magenta                    { 0xFF, 0x00, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Maroon                     { 0x80, 0x00, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumAquaMarine           { 0x66, 0xCD, 0xAA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumBlue                 { 0x00, 0x00, 0xCD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumOrchid               { 0xBA, 0x55, 0xD3, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumPurple               { 0x93, 0x70, 0xDB, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumSeagreen             { 0x3C, 0xB3, 0x71, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumSlateBlue            { 0x7B, 0x68, 0xEE, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumSpringGreen          { 0x00, 0xFA, 0x9A, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumTurquoise            { 0x48, 0xD1, 0xCC, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MediumVioletRed            { 0xC7, 0x15, 0x85, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MidnightBlue               { 0x19, 0x19, 0x70, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::MintCream                  { 0xF5, 0xFF, 0xFA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Mistyrose                  { 0xFF, 0xE4, 0xE1, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Moccasin                   { 0xFF, 0xE4, 0xB5, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::NavajoWhite                { 0xFF, 0xDE, 0xAD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Navy                       { 0x00, 0x00, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Oldlace                    { 0xFD, 0xF5, 0xE6, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Olive                      { 0x80, 0x80, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Olivedrab                  { 0x6B, 0x8E, 0x23, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Orange                     { 0xFF, 0xA5, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Orangered                  { 0xFF, 0x45, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Orchid                     { 0xDA, 0x70, 0xD6, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::PaleGoldenRod              { 0xEE, 0xE8, 0xAA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::PaleGreen                  { 0x98, 0xFB, 0x98, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::PaleTurquoise              { 0xAF, 0xEE, 0xEE, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::PaleVioletRed              { 0xDB, 0x70, 0x93, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Papayawhip                 { 0xFF, 0xEF, 0xD5, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Peachpuff                  { 0xFF, 0xDA, 0xB9, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Peru                       { 0xCD, 0x85, 0x3F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Pink                       { 0xFF, 0xC0, 0xCB, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Plum                       { 0xDD, 0xA0, 0xDD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::PowderBlue                 { 0xB0, 0xE0, 0xE6, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Purple                     { 0x80, 0x00, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::RebeccaPurple              { 0x66, 0x33, 0x99, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Red                        { 0xFF, 0x00, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::RosyBrown                  { 0xBC, 0x8F, 0x8F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::RoyalBlue                  { 0x41, 0x69, 0xE1, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SaddleBrown                { 0x8B, 0x45, 0x13, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Salmon                     { 0xFA, 0x80, 0x72, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SandyBrown                 { 0xF4, 0xA4, 0x60, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SeaGreen                   { 0x2E, 0x8B, 0x57, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Seashell                   { 0xFF, 0xF5, 0xEE, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Sienna                     { 0xA0, 0x52, 0x2D, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Silver                     { 0xC0, 0xC0, 0xC0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SkyBlue                    { 0x87, 0xCE, 0xEB, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SlateBlue                  { 0x6A, 0x5A, 0xCD, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SlateGray                  { 0x70, 0x80, 0x90, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SlateGrey                  { 0x70, 0x80, 0x90, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Snow                       { 0xFF, 0xFA, 0xFA, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SpringGreen                { 0x00, 0xFF, 0x7F, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::SteelBlue                  { 0x46, 0x82, 0xB4, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Tan                        { 0xD2, 0xB4, 0x8C, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Teal                       { 0x00, 0x80, 0x80, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Thistle                    { 0xD8, 0xBF, 0xD8, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Tomato                     { 0xFF, 0x63, 0x47, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Transparent                { 0x00, 0x00, 0x00, 0x00 };
LAL_API const Jafg::LColor Jafg::LColor::Turquoise                  { 0x40, 0xE0, 0xD0, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Violet                     { 0xEE, 0x82, 0xEE, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Wheat                      { 0xF5, 0xDE, 0xB3, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::White                      { 0xFF, 0xFF, 0xFF, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::WhiteSmoke                 { 0xF5, 0xF5, 0xF5, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::Yellow                     { 0xFF, 0xFF, 0x00, 0xFF };
LAL_API const Jafg::LColor Jafg::LColor::YellowGreen                { 0x9A, 0xCD, 0x32, 0xFF };
