// Copyright mzoesch. All rights reserved.

#include "Maths/Color.h"

LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkerGray                 { Lal::LLinearColor::FromColor( 0x1A, 0x1A, 0x1A, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkerGrey                 { Lal::LLinearColor::FromColor( 0x1A, 0x1A, 0x1A, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::NotSoDarkGray              { Lal::LLinearColor::FromColor( 0x2B, 0x2B, 0x2B, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::NotSoDarkGrey              { Lal::LLinearColor::FromColor( 0x2B, 0x2B, 0x2B, 0xFF ) };

LAL_API const Lal::LLinearColor Lal::LLinearColor::Aliceblue                  { Lal::LLinearColor::FromColor( 0xF0, 0xF8, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Antiquewhite               { Lal::LLinearColor::FromColor( 0xFA, 0xEB, 0xD7, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Aqua                       { Lal::LLinearColor::FromColor( 0x00, 0xFF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Aquamarine                 { Lal::LLinearColor::FromColor( 0x7F, 0xFF, 0xD4, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Azure                      { Lal::LLinearColor::FromColor( 0xF0, 0xFF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Beige                      { Lal::LLinearColor::FromColor( 0xF5, 0xF5, 0xDC, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Bisque                     { Lal::LLinearColor::FromColor( 0xFF, 0xE4, 0xC4, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Black                      { Lal::LLinearColor::FromColor( 0x00, 0x00, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Blanchedalmond             { Lal::LLinearColor::FromColor( 0xFF, 0xEB, 0xCD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Blue                       { Lal::LLinearColor::FromColor( 0x00, 0x00, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::BlueViolet                 { Lal::LLinearColor::FromColor( 0x8A, 0x2B, 0xE2, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Brown                      { Lal::LLinearColor::FromColor( 0xA5, 0x2A, 0x2A, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::BurlyWood                  { Lal::LLinearColor::FromColor( 0xDE, 0xB8, 0x87, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::CadetBlue                  { Lal::LLinearColor::FromColor( 0x5F, 0x9E, 0xA0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Chartreuse                 { Lal::LLinearColor::FromColor( 0x7F, 0xFF, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Chocolate                  { Lal::LLinearColor::FromColor( 0xD2, 0x69, 0x1E, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Coral                      { Lal::LLinearColor::FromColor( 0xFF, 0x7F, 0x50, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::CornflowerBlue             { Lal::LLinearColor::FromColor( 0x64, 0x95, 0xED, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Cornsilk                   { Lal::LLinearColor::FromColor( 0xFF, 0xF8, 0xDC, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Crimson                    { Lal::LLinearColor::FromColor( 0xDC, 0x14, 0x3C, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Cyan                       { Lal::LLinearColor::FromColor( 0x00, 0xFF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkBlue                   { Lal::LLinearColor::FromColor( 0x00, 0x00, 0x8B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkCyan                   { Lal::LLinearColor::FromColor( 0x00, 0x8B, 0x8B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkGoldenRod              { Lal::LLinearColor::FromColor( 0xB8, 0x86, 0x0B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkGray                   { Lal::LLinearColor::FromColor( 0xA9, 0xA9, 0xA9, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkGreen                  { Lal::LLinearColor::FromColor( 0x00, 0x64, 0x00, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkGrey                   { Lal::LLinearColor::FromColor( 0xA9, 0xA9, 0xA9, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkKhaki                  { Lal::LLinearColor::FromColor( 0xBD, 0xB7, 0x6B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkMagenta                { Lal::LLinearColor::FromColor( 0x8B, 0x00, 0x8B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkOliveGreen             { Lal::LLinearColor::FromColor( 0x55, 0x6B, 0x2F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkOrange                 { Lal::LLinearColor::FromColor( 0xFF, 0x8C, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkOrchid                 { Lal::LLinearColor::FromColor( 0x99, 0x32, 0xCC, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkRed                    { Lal::LLinearColor::FromColor( 0x8B, 0x00, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkSalmon                 { Lal::LLinearColor::FromColor( 0xE9, 0x96, 0x7A, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkSeaGreen               { Lal::LLinearColor::FromColor( 0x8F, 0xBC, 0x8F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkSlateBlue              { Lal::LLinearColor::FromColor( 0x48, 0x3D, 0x8B, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkSlateGray              { Lal::LLinearColor::FromColor( 0x2F, 0x4F, 0x4F, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkSlateGrey              { Lal::LLinearColor::FromColor( 0x2F, 0x4F, 0x4F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkTurquoise              { Lal::LLinearColor::FromColor( 0x00, 0xCE, 0xD1, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DarkViolet                 { Lal::LLinearColor::FromColor( 0x94, 0x00, 0xD3, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DeepPink                   { Lal::LLinearColor::FromColor( 0xFF, 0x14, 0x93, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DeepSkyBlue                { Lal::LLinearColor::FromColor( 0x00, 0xBF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DimGray                    { Lal::LLinearColor::FromColor( 0x69, 0x69, 0x69, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::DimGrey                    { Lal::LLinearColor::FromColor( 0x69, 0x69, 0x69, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::DodgerBlue                 { Lal::LLinearColor::FromColor( 0x1E, 0x90, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::FireBrick                  { Lal::LLinearColor::FromColor( 0xB2, 0x22, 0x22, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::FloralWhite                { Lal::LLinearColor::FromColor( 0xFF, 0xFA, 0xF0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::ForestGreen                { Lal::LLinearColor::FromColor( 0x22, 0x8B, 0x22, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Fuchsia                    { Lal::LLinearColor::FromColor( 0xFF, 0x00, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Gainsboro                  { Lal::LLinearColor::FromColor( 0xDC, 0xDC, 0xDC, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::GhostWhite                 { Lal::LLinearColor::FromColor( 0xF8, 0xF8, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Gold                       { Lal::LLinearColor::FromColor( 0xFF, 0xD7, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Goldenrod                  { Lal::LLinearColor::FromColor( 0xDA, 0xA5, 0x20, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Gray                       { Lal::LLinearColor::FromColor( 0x80, 0x80, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Green                      { Lal::LLinearColor::FromColor( 0x00, 0x80, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::GreenYellow                { Lal::LLinearColor::FromColor( 0xAD, 0xFF, 0x2F, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::Grey                       { Lal::LLinearColor::FromColor( 0x80, 0x80, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Honeydew                   { Lal::LLinearColor::FromColor( 0xF0, 0xFF, 0xF0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::HotPink                    { Lal::LLinearColor::FromColor( 0xFF, 0x69, 0xB4, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Indianred                  { Lal::LLinearColor::FromColor( 0xCD, 0x5C, 0x5C, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Indigo                     { Lal::LLinearColor::FromColor( 0x4B, 0x00, 0x82, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Ivory                      { Lal::LLinearColor::FromColor( 0xFF, 0xFF, 0xF0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Khaki                      { Lal::LLinearColor::FromColor( 0xF0, 0xE6, 0x8C, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Lavender                   { Lal::LLinearColor::FromColor( 0xE6, 0xE6, 0xFA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LavenderBlush              { Lal::LLinearColor::FromColor( 0xFF, 0xF0, 0xF5, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LawnGreen                  { Lal::LLinearColor::FromColor( 0x7C, 0xFC, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LemonChiffon               { Lal::LLinearColor::FromColor( 0xFF, 0xFA, 0xCD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightBlue                  { Lal::LLinearColor::FromColor( 0xAD, 0xD8, 0xE6, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightCoral                 { Lal::LLinearColor::FromColor( 0xF0, 0x80, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightCyan                  { Lal::LLinearColor::FromColor( 0xE0, 0xFF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightGoldenrodYellow       { Lal::LLinearColor::FromColor( 0xFA, 0xFA, 0xD2, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightGray                  { Lal::LLinearColor::FromColor( 0xD3, 0xD3, 0xD3, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightGreen                 { Lal::LLinearColor::FromColor( 0x90, 0xEE, 0x90, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::LightGrey                  { Lal::LLinearColor::FromColor( 0xD3, 0xD3, 0xD3, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightPink                  { Lal::LLinearColor::FromColor( 0xFF, 0xB6, 0xC1, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSalmon                { Lal::LLinearColor::FromColor( 0xFF, 0xA0, 0x7A, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSeagreen              { Lal::LLinearColor::FromColor( 0x20, 0xB2, 0xAA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSkyBlue               { Lal::LLinearColor::FromColor( 0x87, 0xCE, 0xFA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSlateGray             { Lal::LLinearColor::FromColor( 0x77, 0x88, 0x99, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSlateGrey             { Lal::LLinearColor::FromColor( 0x77, 0x88, 0x99, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightSteelBlue             { Lal::LLinearColor::FromColor( 0xB0, 0xC4, 0xDE, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LightYellow                { Lal::LLinearColor::FromColor( 0xFF, 0xFF, 0xE0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Lime                       { Lal::LLinearColor::FromColor( 0x00, 0xFF, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::LimeGreen                  { Lal::LLinearColor::FromColor( 0x32, 0xCD, 0x32, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Linen                      { Lal::LLinearColor::FromColor( 0xFA, 0xF0, 0xE6, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Magenta                    { Lal::LLinearColor::FromColor( 0xFF, 0x00, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Maroon                     { Lal::LLinearColor::FromColor( 0x80, 0x00, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumAquaMarine           { Lal::LLinearColor::FromColor( 0x66, 0xCD, 0xAA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumBlue                 { Lal::LLinearColor::FromColor( 0x00, 0x00, 0xCD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumOrchid               { Lal::LLinearColor::FromColor( 0xBA, 0x55, 0xD3, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumPurple               { Lal::LLinearColor::FromColor( 0x93, 0x70, 0xDB, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumSeagreen             { Lal::LLinearColor::FromColor( 0x3C, 0xB3, 0x71, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumSlateBlue            { Lal::LLinearColor::FromColor( 0x7B, 0x68, 0xEE, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumSpringGreen          { Lal::LLinearColor::FromColor( 0x00, 0xFA, 0x9A, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumTurquoise            { Lal::LLinearColor::FromColor( 0x48, 0xD1, 0xCC, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MediumVioletRed            { Lal::LLinearColor::FromColor( 0xC7, 0x15, 0x85, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MidnightBlue               { Lal::LLinearColor::FromColor( 0x19, 0x19, 0x70, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::MintCream                  { Lal::LLinearColor::FromColor( 0xF5, 0xFF, 0xFA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Mistyrose                  { Lal::LLinearColor::FromColor( 0xFF, 0xE4, 0xE1, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Moccasin                   { Lal::LLinearColor::FromColor( 0xFF, 0xE4, 0xB5, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::NavajoWhite                { Lal::LLinearColor::FromColor( 0xFF, 0xDE, 0xAD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Navy                       { Lal::LLinearColor::FromColor( 0x00, 0x00, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Oldlace                    { Lal::LLinearColor::FromColor( 0xFD, 0xF5, 0xE6, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Olive                      { Lal::LLinearColor::FromColor( 0x80, 0x80, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Olivedrab                  { Lal::LLinearColor::FromColor( 0x6B, 0x8E, 0x23, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Orange                     { Lal::LLinearColor::FromColor( 0xFF, 0xA5, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Orangered                  { Lal::LLinearColor::FromColor( 0xFF, 0x45, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Orchid                     { Lal::LLinearColor::FromColor( 0xDA, 0x70, 0xD6, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::PaleGoldenRod              { Lal::LLinearColor::FromColor( 0xEE, 0xE8, 0xAA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::PaleGreen                  { Lal::LLinearColor::FromColor( 0x98, 0xFB, 0x98, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::PaleTurquoise              { Lal::LLinearColor::FromColor( 0xAF, 0xEE, 0xEE, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::PaleVioletRed              { Lal::LLinearColor::FromColor( 0xDB, 0x70, 0x93, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Papayawhip                 { Lal::LLinearColor::FromColor( 0xFF, 0xEF, 0xD5, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Peachpuff                  { Lal::LLinearColor::FromColor( 0xFF, 0xDA, 0xB9, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Peru                       { Lal::LLinearColor::FromColor( 0xCD, 0x85, 0x3F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Pink                       { Lal::LLinearColor::FromColor( 0xFF, 0xC0, 0xCB, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Plum                       { Lal::LLinearColor::FromColor( 0xDD, 0xA0, 0xDD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::PowderBlue                 { Lal::LLinearColor::FromColor( 0xB0, 0xE0, 0xE6, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Purple                     { Lal::LLinearColor::FromColor( 0x80, 0x00, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::RebeccaPurple              { Lal::LLinearColor::FromColor( 0x66, 0x33, 0x99, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Red                        { Lal::LLinearColor::FromColor( 0xFF, 0x00, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::RosyBrown                  { Lal::LLinearColor::FromColor( 0xBC, 0x8F, 0x8F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::RoyalBlue                  { Lal::LLinearColor::FromColor( 0x41, 0x69, 0xE1, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SaddleBrown                { Lal::LLinearColor::FromColor( 0x8B, 0x45, 0x13, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Salmon                     { Lal::LLinearColor::FromColor( 0xFA, 0x80, 0x72, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SandyBrown                 { Lal::LLinearColor::FromColor( 0xF4, 0xA4, 0x60, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SeaGreen                   { Lal::LLinearColor::FromColor( 0x2E, 0x8B, 0x57, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Seashell                   { Lal::LLinearColor::FromColor( 0xFF, 0xF5, 0xEE, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Sienna                     { Lal::LLinearColor::FromColor( 0xA0, 0x52, 0x2D, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Silver                     { Lal::LLinearColor::FromColor( 0xC0, 0xC0, 0xC0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SkyBlue                    { Lal::LLinearColor::FromColor( 0x87, 0xCE, 0xEB, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SlateBlue                  { Lal::LLinearColor::FromColor( 0x6A, 0x5A, 0xCD, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SlateGray                  { Lal::LLinearColor::FromColor( 0x70, 0x80, 0x90, 0xFF ) };
// LAL_API const Lal::LLinearColor Lal::LLinearColor::SlateGrey                  { Lal::LLinearColor::FromColor( 0x70, 0x80, 0x90, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Snow                       { Lal::LLinearColor::FromColor( 0xFF, 0xFA, 0xFA, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SpringGreen                { Lal::LLinearColor::FromColor( 0x00, 0xFF, 0x7F, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::SteelBlue                  { Lal::LLinearColor::FromColor( 0x46, 0x82, 0xB4, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Tan                        { Lal::LLinearColor::FromColor( 0xD2, 0xB4, 0x8C, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Teal                       { Lal::LLinearColor::FromColor( 0x00, 0x80, 0x80, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Thistle                    { Lal::LLinearColor::FromColor( 0xD8, 0xBF, 0xD8, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Tomato                     { Lal::LLinearColor::FromColor( 0xFF, 0x63, 0x47, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Transparent                { Lal::LLinearColor::FromColor( 0x00, 0x00, 0x00, 0x00 ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Turquoise                  { Lal::LLinearColor::FromColor( 0x40, 0xE0, 0xD0, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Violet                     { Lal::LLinearColor::FromColor( 0xEE, 0x82, 0xEE, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Wheat                      { Lal::LLinearColor::FromColor( 0xF5, 0xDE, 0xB3, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::White                      { Lal::LLinearColor::FromColor( 0xFF, 0xFF, 0xFF, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::WhiteSmoke                 { Lal::LLinearColor::FromColor( 0xF5, 0xF5, 0xF5, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::Yellow                     { Lal::LLinearColor::FromColor( 0xFF, 0xFF, 0x00, 0xFF ) };
LAL_API const Lal::LLinearColor Lal::LLinearColor::YellowGreen                { Lal::LLinearColor::FromColor( 0x9A, 0xCD, 0x32, 0xFF ) };

LAL_API const Lal::LColor Lal::LColor::DarkerGray                 { 0x1A, 0x1A, 0x1A, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::DarkerGrey                 { 0x1A, 0x1A, 0x1A, 0xFF };
LAL_API const Lal::LColor Lal::LColor::NotSoDarkGray              { 0x2B, 0x2B, 0x2B, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::NotSoDarkGrey              { 0x2B, 0x2B, 0x2B, 0xFF };

LAL_API const Lal::LColor Lal::LColor::Aliceblue                  { 0xF0, 0xF8, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Antiquewhite               { 0xFA, 0xEB, 0xD7, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Aqua                       { 0x00, 0xFF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Aquamarine                 { 0x7F, 0xFF, 0xD4, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Azure                      { 0xF0, 0xFF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Beige                      { 0xF5, 0xF5, 0xDC, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Bisque                     { 0xFF, 0xE4, 0xC4, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Black                      { 0x00, 0x00, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Blanchedalmond             { 0xFF, 0xEB, 0xCD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Blue                       { 0x00, 0x00, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::BlueViolet                 { 0x8A, 0x2B, 0xE2, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Brown                      { 0xA5, 0x2A, 0x2A, 0xFF };
LAL_API const Lal::LColor Lal::LColor::BurlyWood                  { 0xDE, 0xB8, 0x87, 0xFF };
LAL_API const Lal::LColor Lal::LColor::CadetBlue                  { 0x5F, 0x9E, 0xA0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Chartreuse                 { 0x7F, 0xFF, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Chocolate                  { 0xD2, 0x69, 0x1E, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Coral                      { 0xFF, 0x7F, 0x50, 0xFF };
LAL_API const Lal::LColor Lal::LColor::CornflowerBlue             { 0x64, 0x95, 0xED, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Cornsilk                   { 0xFF, 0xF8, 0xDC, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Crimson                    { 0xDC, 0x14, 0x3C, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Cyan                       { 0x00, 0xFF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkBlue                   { 0x00, 0x00, 0x8B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkCyan                   { 0x00, 0x8B, 0x8B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkGoldenRod              { 0xB8, 0x86, 0x0B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkGray                   { 0xA9, 0xA9, 0xA9, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkGreen                  { 0x00, 0x64, 0x00, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::DarkGrey                   { 0xA9, 0xA9, 0xA9, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkKhaki                  { 0xBD, 0xB7, 0x6B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkMagenta                { 0x8B, 0x00, 0x8B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkOliveGreen             { 0x55, 0x6B, 0x2F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkOrange                 { 0xFF, 0x8C, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkOrchid                 { 0x99, 0x32, 0xCC, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkRed                    { 0x8B, 0x00, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkSalmon                 { 0xE9, 0x96, 0x7A, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkSeaGreen               { 0x8F, 0xBC, 0x8F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkSlateBlue              { 0x48, 0x3D, 0x8B, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkSlateGray              { 0x2F, 0x4F, 0x4F, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::DarkSlateGrey              { 0x2F, 0x4F, 0x4F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkTurquoise              { 0x00, 0xCE, 0xD1, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DarkViolet                 { 0x94, 0x00, 0xD3, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DeepPink                   { 0xFF, 0x14, 0x93, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DeepSkyBlue                { 0x00, 0xBF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DimGray                    { 0x69, 0x69, 0x69, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::DimGrey                    { 0x69, 0x69, 0x69, 0xFF };
LAL_API const Lal::LColor Lal::LColor::DodgerBlue                 { 0x1E, 0x90, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::FireBrick                  { 0xB2, 0x22, 0x22, 0xFF };
LAL_API const Lal::LColor Lal::LColor::FloralWhite                { 0xFF, 0xFA, 0xF0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::ForestGreen                { 0x22, 0x8B, 0x22, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Fuchsia                    { 0xFF, 0x00, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Gainsboro                  { 0xDC, 0xDC, 0xDC, 0xFF };
LAL_API const Lal::LColor Lal::LColor::GhostWhite                 { 0xF8, 0xF8, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Gold                       { 0xFF, 0xD7, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Goldenrod                  { 0xDA, 0xA5, 0x20, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Gray                       { 0x80, 0x80, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Green                      { 0x00, 0x80, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::GreenYellow                { 0xAD, 0xFF, 0x2F, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::Grey                       { 0x80, 0x80, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Honeydew                   { 0xF0, 0xFF, 0xF0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::HotPink                    { 0xFF, 0x69, 0xB4, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Indianred                  { 0xCD, 0x5C, 0x5C, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Indigo                     { 0x4B, 0x00, 0x82, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Ivory                      { 0xFF, 0xFF, 0xF0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Khaki                      { 0xF0, 0xE6, 0x8C, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Lavender                   { 0xE6, 0xE6, 0xFA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LavenderBlush              { 0xFF, 0xF0, 0xF5, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LawnGreen                  { 0x7C, 0xFC, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LemonChiffon               { 0xFF, 0xFA, 0xCD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightBlue                  { 0xAD, 0xD8, 0xE6, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightCoral                 { 0xF0, 0x80, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightCyan                  { 0xE0, 0xFF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightGoldenrodYellow       { 0xFA, 0xFA, 0xD2, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightGray                  { 0xD3, 0xD3, 0xD3, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightGreen                 { 0x90, 0xEE, 0x90, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::LightGrey                  { 0xD3, 0xD3, 0xD3, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightPink                  { 0xFF, 0xB6, 0xC1, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightSalmon                { 0xFF, 0xA0, 0x7A, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightSeagreen              { 0x20, 0xB2, 0xAA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightSkyBlue               { 0x87, 0xCE, 0xFA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightSlateGray             { 0x77, 0x88, 0x99, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::LightSlateGrey             { 0x77, 0x88, 0x99, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightSteelBlue             { 0xB0, 0xC4, 0xDE, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LightYellow                { 0xFF, 0xFF, 0xE0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Lime                       { 0x00, 0xFF, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::LimeGreen                  { 0x32, 0xCD, 0x32, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Linen                      { 0xFA, 0xF0, 0xE6, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Magenta                    { 0xFF, 0x00, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Maroon                     { 0x80, 0x00, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumAquaMarine           { 0x66, 0xCD, 0xAA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumBlue                 { 0x00, 0x00, 0xCD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumOrchid               { 0xBA, 0x55, 0xD3, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumPurple               { 0x93, 0x70, 0xDB, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumSeagreen             { 0x3C, 0xB3, 0x71, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumSlateBlue            { 0x7B, 0x68, 0xEE, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumSpringGreen          { 0x00, 0xFA, 0x9A, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumTurquoise            { 0x48, 0xD1, 0xCC, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MediumVioletRed            { 0xC7, 0x15, 0x85, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MidnightBlue               { 0x19, 0x19, 0x70, 0xFF };
LAL_API const Lal::LColor Lal::LColor::MintCream                  { 0xF5, 0xFF, 0xFA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Mistyrose                  { 0xFF, 0xE4, 0xE1, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Moccasin                   { 0xFF, 0xE4, 0xB5, 0xFF };
LAL_API const Lal::LColor Lal::LColor::NavajoWhite                { 0xFF, 0xDE, 0xAD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Navy                       { 0x00, 0x00, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Oldlace                    { 0xFD, 0xF5, 0xE6, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Olive                      { 0x80, 0x80, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Olivedrab                  { 0x6B, 0x8E, 0x23, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Orange                     { 0xFF, 0xA5, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Orangered                  { 0xFF, 0x45, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Orchid                     { 0xDA, 0x70, 0xD6, 0xFF };
LAL_API const Lal::LColor Lal::LColor::PaleGoldenRod              { 0xEE, 0xE8, 0xAA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::PaleGreen                  { 0x98, 0xFB, 0x98, 0xFF };
LAL_API const Lal::LColor Lal::LColor::PaleTurquoise              { 0xAF, 0xEE, 0xEE, 0xFF };
LAL_API const Lal::LColor Lal::LColor::PaleVioletRed              { 0xDB, 0x70, 0x93, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Papayawhip                 { 0xFF, 0xEF, 0xD5, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Peachpuff                  { 0xFF, 0xDA, 0xB9, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Peru                       { 0xCD, 0x85, 0x3F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Pink                       { 0xFF, 0xC0, 0xCB, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Plum                       { 0xDD, 0xA0, 0xDD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::PowderBlue                 { 0xB0, 0xE0, 0xE6, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Purple                     { 0x80, 0x00, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::RebeccaPurple              { 0x66, 0x33, 0x99, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Red                        { 0xFF, 0x00, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::RosyBrown                  { 0xBC, 0x8F, 0x8F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::RoyalBlue                  { 0x41, 0x69, 0xE1, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SaddleBrown                { 0x8B, 0x45, 0x13, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Salmon                     { 0xFA, 0x80, 0x72, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SandyBrown                 { 0xF4, 0xA4, 0x60, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SeaGreen                   { 0x2E, 0x8B, 0x57, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Seashell                   { 0xFF, 0xF5, 0xEE, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Sienna                     { 0xA0, 0x52, 0x2D, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Silver                     { 0xC0, 0xC0, 0xC0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SkyBlue                    { 0x87, 0xCE, 0xEB, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SlateBlue                  { 0x6A, 0x5A, 0xCD, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SlateGray                  { 0x70, 0x80, 0x90, 0xFF };
// LAL_API const Lal::LColor Lal::LColor::SlateGrey                  { 0x70, 0x80, 0x90, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Snow                       { 0xFF, 0xFA, 0xFA, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SpringGreen                { 0x00, 0xFF, 0x7F, 0xFF };
LAL_API const Lal::LColor Lal::LColor::SteelBlue                  { 0x46, 0x82, 0xB4, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Tan                        { 0xD2, 0xB4, 0x8C, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Teal                       { 0x00, 0x80, 0x80, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Thistle                    { 0xD8, 0xBF, 0xD8, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Tomato                     { 0xFF, 0x63, 0x47, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Transparent                { 0x00, 0x00, 0x00, 0x00 };
LAL_API const Lal::LColor Lal::LColor::Turquoise                  { 0x40, 0xE0, 0xD0, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Violet                     { 0xEE, 0x82, 0xEE, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Wheat                      { 0xF5, 0xDE, 0xB3, 0xFF };
LAL_API const Lal::LColor Lal::LColor::White                      { 0xFF, 0xFF, 0xFF, 0xFF };
LAL_API const Lal::LColor Lal::LColor::WhiteSmoke                 { 0xF5, 0xF5, 0xF5, 0xFF };
LAL_API const Lal::LColor Lal::LColor::Yellow                     { 0xFF, 0xFF, 0x00, 0xFF };
LAL_API const Lal::LColor Lal::LColor::YellowGreen                { 0x9A, 0xCD, 0x32, 0xFF };
