// Copyright mzoesch. All rights reserved.

mod module_kind;
mod finder;
mod paths;
mod reflector;
mod tokenizer;

use clap::Parser;
use module_kind::ModuleKind;

/// Main CLI structure for the motor of Jafg.
#[derive(clap::Parser, Debug)]
#[command(author, version, about)]
struct Cli
{
    /// Whether to emit verbose output.
    #[arg(long = "Verbose", default_value_t = false)]
    verbose: bool,

    /// The module to build for.
    #[arg(long = "Module")]
    module: String,

    /// The platform to build for.
    #[arg(long = "Platform")]
    platform: String,

    /// The architecture to build for.
    #[arg(long = "Architecture")]
    architecture: String,

    /// The target to build for.
    #[arg(long = "Target")]
    target: String,

    /// The configuration to build for.
    #[arg(long = "Configuration")]
    config: String,

    /// The kind of the module to build.
    #[arg(long = "Kind")]
    kind: ModuleKind,
}

fn main()
{
    let cwd: std::path::PathBuf = std::env::current_dir().unwrap();
    let new_cwd: String = paths::get_engine_root_dir();
    std::env::set_current_dir(&new_cwd).unwrap();

    let args: Cli = Cli::parse();

    if args.verbose
    {
        println!("Launching pre-build for [{}] ...", args.module);
    }

    /*
     * Construct paths so we do not have to deal with missing dirs when crating random files in
     * them - some platforms forbid to create files in dirs that don't exist.
     * Also better for the target IDE performance.
     */
    finder::ensure_path(&paths::construct_relative_gh_path(&args));
    finder::ensure_path(&paths::construct_relative_gt_path(&args));

    /*
     * Reflect the module by gathering all necessary packages and exporting their macros.
     */
    reflector::reflect_module(&args);

    /*
     * Search for a unit test file in the module's test source directory and supply the compiler
     * with their definitions.
     */
    if args.target == "TestUnit"
    {
        /*
         * The file to the header that marks the module as a module that uses the default
         * simple test registration procedure.
         * A module might still register its own test that are not inside the TestModule.h file,
         * but they will then have to handle the registration themselves - we simply do not care.
         */
        let test_module_f: String = format!("{}/TestModule.h", paths::get_relative_source_dir_test(&args));

        /*
         * The path to the translation file that contains the module files of unit tests
         * if the module uses the default simple test registration procedure.
         */
        let test_module_t: String = format!("{}/_TestModule.generated.cpp", paths::construct_relative_gt_path(&args));

        if finder::exists_file(test_module_f.as_str())
        {
            if args.verbose
            {
                println!("[{}]: Found module test file. Creating auto unit test registration files.", test_module_f);
            }

            let mut t_builder: String = String::new();
            t_builder.push_str(&format!(r##"
// Copyright mzoesch. All rights reserved.

/*-----------------------------------------------------------------------------
    This translation file was generated by the Jafg build tool.
    Do not modify it manually.
-----------------------------------------------------------------------------*/

#ifdef PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION
    #undef PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION
#endif /* PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION */
#define PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION               1

#include "{test_module_f}"

#ifdef PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION
    #undef PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION
#endif /* PRIVATE_JAFG_INCLUDED_FROM_GENERATED_TRANSLATION */

"##,
            ));

            finder::write_to_file_if_different(&test_module_t, args.verbose, &t_builder);
        }
        else
        {
            if finder::exists_file(test_module_t.as_str())
            {
                if args.verbose
                {
                    println!("[{}]: Auto registration file exists but the module no longer uses the default automatic unit test registration procedure.", test_module_t);
                }

                finder::delete_file(test_module_t.as_str());
            }
        }
    }

    std::env::set_current_dir(cwd).unwrap();
    std::process::exit(0);
}
