# Copyright mzoesch. All rights reserved.

###############################################################################
# Validate the compiler and its flags.
###############################################################################

function(JafgIsCompilerClang RESULT)
    string(REGEX MATCH ".*clang\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
    if(REGREX_MATCHED)
        set(${RESULT} TRUE PARENT_SCOPE)
    else()
        set(${RESULT} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(JafgIsCompilerMsvc RESULT)
    string(REGEX MATCH ".*cl\\.exe.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
    if(REGREX_MATCHED)
        set(${RESULT} TRUE PARENT_SCOPE)
    else()
        set(${RESULT} FALSE PARENT_SCOPE)
    endif()
endfunction()

if(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_LINUX)
    message(STATUS "Checking C and C++ compiler for linux platform.")
    if(NOT DEFINED CMAKE_C_COMPILER)
        message(STATUS "Defaulting to C compiler [clang] on linux.")
        set(CMAKE_C_COMPILER "clang")
    endif()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        message(STATUS "Defaulting to C++ compiler [clang++] on linux.")
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
    string(REGEX MATCH ".*clang\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
    if(NOT REGREX_MATCHED)
        message(STATUS "Changing C and C++ compiler from [${CMAKE_C_COMPILER}] and [${CMAKE_CXX_COMPILER}] to clang and clang++ respectively.")
        set(CMAKE_C_COMPILER "clang")
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
elseif(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_WINDOWS)
    message(STATUS "Checking C and C++ compiler for windows platform.")
    if(NOT DEFINED CMAKE_C_COMPILER)
        message(STATUS "Defaulting to C compiler [clang.exe] on windows.")
        set(CMAKE_C_COMPILER "clang.exe")
    endif()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        message(STATUS "Defaulting to C++ compiler [clang++.exe] on windows.")
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
    JafgIsCompilerClang(IS_CLANG)
    JafgIsCompilerMsvc(IS_MSVC)
    if(NOT IS_CLANG AND NOT IS_MSVC)
        message(FATAL_ERROR "CXX compiler [CLANG] or [MSVC] is required for this platform [${JAFG_TARGET_PLATFORM}]. Current compilers are [${CMAKE_C_COMPILER}] and [${CMAKE_CXX_COMPILER}].")
    endif()
elseif(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_WASM)
    if(DEFINED CMAKE_CXX_COMPILER)
        if(NOT CMAKE_CXX_COMPILER STREQUAL "")
            string(REGEX MATCH ".*em\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
            if(NOT REGREX_MATCHED)
                message(FATAL_ERROR "CXX compiler [EM] is required for this platform [${JAFG_TARGET_PLATFORM}].")
            endif()
        endif()
    endif()
else()
    message(FATAL_ERROR "Missing implementation here for JAFG_TARGET_PLATFORM [${JAFG_TARGET_PLATFORM}].")
endif()
