###############################################################################
# Validate the compiler and its flags.
###############################################################################

if(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_LINUX)
    message(STATUS "Checking C and C++ compiler for linux platform.")
    if(NOT DEFINED CMAKE_C_COMPILER)
        message(STATUS "Defaulting to C compiler [clang] on linux.")
        set(CMAKE_C_COMPILER "clang")
    endif()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        message(STATUS "Defaulting to C++ compiler [clang++] on linux.")
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
    string(REGEX MATCH ".*clang\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
    if(NOT REGREX_MATCHED)
        message(STATUS "Changing C and C++ compiler from [${CMAKE_C_COMPILER}] and [${CMAKE_CXX_COMPILER}] to clang and clang++ respectively.")
        set(CMAKE_C_COMPILER "clang")
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
elseif(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_WINDOWS)
    message(STATUS "Changing C and C++ compiler from [${CMAKE_C_COMPILER}] and [${CMAKE_CXX_COMPILER}] to cl.exe.")
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(CMAKE_C_COMPILER "cl.exe")
        set(CMAKE_CXX_COMPILER "cl.exe")
    endif()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:__cplusplus /GR- /MP")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:MSVCRT")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SUBSYSTEM:WINDOWS /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:MSVCRT")
    set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:MSVCRT")
elseif(JAFG_TARGET_PLATFORM STREQUAL JAFG_PLATFORM_WASM)
    if(DEFINED CMAKE_CXX_COMPILER)
        if(NOT CMAKE_CXX_COMPILER STREQUAL "")
            string(REGEX MATCH ".*em\\+\\+.*" REGREX_MATCHED ${CMAKE_CXX_COMPILER})
            if(NOT REGREX_MATCHED)
                message(FATAL_ERROR "CXX compiler [EM] is required for this platform [${JAFG_TARGET_PLATFORM}].")
            endif()
        endif()
    endif()
else()
    message(FATAL_ERROR "Missing implementation here for JAFG_TARGET_PLATFORM [${JAFG_TARGET_PLATFORM}].")
endif()

