name: Notify Rest Motor API

on:
  push:
    branches: [trunk]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Rest Motor API
        env:
          SECRET_X_HUB_SIGNATURE: ${{ secrets.SECRET_X_HUB_SIGNATURE }}
          REST_API_ENDPOINT: ${{ secrets.REST_API_ENDPOINT }}
        run: |
          payload='{"message": "Triggered by GitHub Action"}'
          signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "$SECRET_X_HUB_SIGNATURE" | sed 's/^.* //')
          curl -X POST $REST_API_ENDPOINT \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$signature" \
            -d "$payload"
