// Copyright mzoesch. All rights reserved.

package BuildTool

import (
    "Jafg/Core"
    "Jafg/Shared"
    "fmt"
    "os"
    "strings"
)

// Wwi stands for Write With Indentation (abbreviated because used literally in every line here - sorry).
func Wwi(b *strings.Builder, i int, c string) {
    b.WriteString(fmt.Sprintf("%s%s\n", strings.Repeat(" ", i * 4), c))
    return
}
func Wni(b *strings.Builder, c string) {
    b.WriteString(c)
    b.WriteString("\n")
    return
}

func StringToPremakeBool(b bool) string {
    if b {
        return "On"
    }
    return "Off"
}

func GenerateSolutionFromPremake(sln *Core.Solution) error {
    fmt.Printf("Generating premake solution [%s] ...\n", sln.Name)

    var fPath string = Core.MakeFilePath_LuaOut(sln)
    Shared.CheckRelativeFile(fPath)
    var f *os.File = Shared.OpenRelativeFile(fPath, true, os.O_RDWR)
    defer Shared.CloseFile(f)

    Shared.WriteToFile(
        f,
        "-- Copyright mzoesch. All rights reserved.\n"+
            "-- This file is automatically generated by Jafg and can be deleted with no fear.\n\n",
    )

    var builder strings.Builder = strings.Builder{}
    var b *strings.Builder = &builder

    Wni(b, "language 'C++'")
    Wni(b, "cppdialect 'C++20'")

    Wni(b, "workspace 'Jafg'")
    if len(sln.Startup) == 0 {
        panic("Startup project is not set.")
    }
    Wwi(b, 1, fmt.Sprintf("startproject '%s'", sln.Startup))
    Wwi(b, 1, "platforms { 'Windows64', 'Wasm' }")
    for _, t := range sln.Targets {
        if len(t.Name) == 0 {
            panic("Target name is empty.")
        }
        Wwi(b, 1, fmt.Sprintf("configurations { '%s' }", t.Name))
    }
    Wwi(b, 1, "filter { 'platforms:Windows64' }")
    Wwi(b, 2, "system 'Windows'")
    Wwi(b, 2, "systemversion 'latest'")
    Wwi(b, 2, "architecture 'x86_64'")
    Wwi(b, 1, "filter { 'platforms:Wasm' }")
    Wwi(b, 2, "systemversion 'latest'")
    Wwi(b, 2, "system 'wasm'")
    Wwi(b, 2, "architecture 'wasm32'")
    Wwi(b, 1, "filter {}")

    for _, t := range sln.Targets {
        Wwi(b, 1, fmt.Sprintf("filter { 'configurations:%s' }", t.Name))
        Wwi(b, 2, fmt.Sprintf("runtime '%s'", t.Runtime))
        Wwi(b, 2, fmt.Sprintf("symbols '%s'", StringToPremakeBool(t.Symbols)))
        Wwi(b, 2, fmt.Sprintf("optimize '%s'", StringToPremakeBool(t.Optimize)))
        Wwi(b, 2, fmt.Sprintf("defines { '%s' }", strings.Join(t.Defines, "', '")))
        Wwi(b, 1, "filter {}")
    }



    Shared.WriteToFile(f, b.String())
    fmt.Println("Finished generating premake solution.")
    return nil
}
