// Copyright 2024 mzoesch. All rights reserved.

package BuildTool

var GeneratedHeaderFileStub string = `
// Copyright mzoesch. All rights reserved.

/*-----------------------------------------------------------------------------
    This header file was generated by the Jafg build tool.
    Do not modify it manually.
-----------------------------------------------------------------------------*/
`

var GeneratedSourceFileStub string = `
// Copyright mzoesch. All rights reserved.

/*-----------------------------------------------------------------------------
    This source file was generated by the Jafg build tool.
    Do not modify it manually.
-----------------------------------------------------------------------------*/
`

var HeaderGuardPostfixStub string = `
/*-----------------------------------------------------------------------------
    BEGIN Generated header content.
-----------------------------------------------------------------------------*/

`
